In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:\\Windows\\Fonts\\malgun.ttf").get_name()
plt.rc("font", family=font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"] = False

import xml.etree.ElementTree as et

import urllib.request as req
import requests
import json

import urllib.request as req
from urllib.error import HTTPError, URLError 

from bs4 import BeautifulSoup

from urllib.request import urlopen

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import os
import re

from scipy.stats import shapiro
from scipy import stats
import scipy

### 범죄

In [3]:
crime = pd.read_csv('C:/acorn/midproject/crimerate/final_crime_gu_year.csv', index_col=0)
crime

    자치구별  2018  2019  2020  2021
0    종로구   364   370   272   271
1     중구   357   314   283   282
2    용산구   417   362   319   248
3    성동구   204   205   171   220
4    광진구   363   415   352   325
5   동대문구   243   249   244   282
6    중랑구   238   212   276   273
7    성북구   303   259   212   222
8    강북구   273   239   217   222
9    도봉구   177   136   131   131
10   노원구   293   272   236   293
11   은평구   312   283   251   293
12  서대문구   278   268   251   292
13   마포구   735   673   577   524
14   양천구   193   199   189   202
15   강서구   424   442   410   434
16   구로구   405   363   344   341
17   금천구   273   221   183   246
18  영등포구   592   520   484   480
19   동작구   416   367   305   304
20   관악구   545   579   557   528
21   서초구   635   785   578   540
22   강남구  1010  1280  1048   946
23   송파구   515   459   444   496
24   강동구   241   280   289   234

In [26]:
crime_long = pd.melt(crime, id_vars=['자치구별'], var_name='계약연도', value_name='범죄건수')
crime_long

   자치구별  계약연도  범죄건수
0   종로구  2018   364
1    중구  2018   357
2   용산구  2018   417
3   성동구  2018   204
4   광진구  2018   363
..  ...   ...   ...
95  관악구  2021   528
96  서초구  2021   540
97  강남구  2021   946
98  송파구  2021   496
99  강동구  2021   234

[100 rows x 3 columns]

### 버스정류장

In [34]:
bus = pd.read_csv('C:/acorn/MidtermProject/프로젝트/팀원들 자료 정리/연도별 서울 정류장수.csv', index_col=0)
del bus['2022정류장수']
bus.drop(index=25, inplace=True)
bus.rename(columns={'2018정류장수':'2018', '2019정류장수':'2019', '2020정류장수':'2020', '2021정류장수':'2021'}, inplace=True)
bus

    자치구별   2018   2019   2020   2021
0    강남구  534.0  548.0  545.0  520.0
1    강동구  349.0  385.0  383.0  365.0
2    강북구  460.0  448.0  415.0  409.0
3    강서구  576.0  603.0  611.0  569.0
4    관악구  485.0  485.0  470.0  467.0
5    광진구  286.0  292.0  288.0  270.0
6    구로구  478.0  513.0  510.0  497.0
7    금천구  342.0  362.0  357.0  342.0
8    노원구  537.0  544.0  538.0  527.0
9    도봉구  386.0  391.0  366.0  358.0
10  동대문구  318.0  319.0  311.0  303.0
11   동작구  460.0  447.0  440.0  437.0
12   마포구  569.0  568.0  570.0  563.0
13  서대문구  444.0  446.0  457.0  454.0
14   서초구  648.0  649.0  638.0  605.0
15   성동구  439.0  442.0  433.0  445.0
16   성북구  611.0  604.0  599.0  601.0
17   송파구  413.0  429.0  440.0  414.0
18   양천구  363.0  365.0  320.0  317.0
19  영등포구  491.0  504.0  494.0  466.0
20   용산구  349.0  344.0  327.0  328.0
21   은평구  499.0  511.0  501.0  497.0
22   종로구  382.0  375.0  374.0  369.0
23    중구  207.0  211.0  241.0  200.0
24   중랑구  379.0  380.0  382.0  380.0

In [35]:
bus_long = pd.melt(bus, id_vars=['자치구별'], var_name='계약연도', value_name='정류장수')
bus_long

   자치구별  계약연도   정류장수
0   강남구  2018  534.0
1   강동구  2018  349.0
2   강북구  2018  460.0
3   강서구  2018  576.0
4   관악구  2018  485.0
..  ...   ...    ...
95  용산구  2021  328.0
96  은평구  2021  497.0
97  종로구  2021  369.0
98   중구  2021  200.0
99  중랑구  2021  380.0

[100 rows x 3 columns]

### 편의점

In [36]:
conve = pd.read_csv('C:/acorn/MidtermProject/프로젝트/팀원들 자료 정리/연도별 서울 편의점수.csv', index_col=0)
del conve['2022편의점수']
conve.drop(index=25, inplace=True)
conve.rename(columns={'2018편의점수':'2018', '2019편의점수':'2019', '2020편의점수':'2020', '2021편의점수':'2021'}, inplace=True)
conve

    자치구별   2018   2019   2020   2021
0    서초구  298.0  314.0  321.0  317.0
1    강남구  558.0  597.0  606.0  615.0
2    동작구  118.0  141.0  147.0  161.0
3    송파구  108.0  123.0  160.0  208.0
4    광진구  137.0  181.0  200.0  220.0
5    용산구  105.0  118.0  129.0  130.0
6   동대문구  154.0  188.0  188.0  204.0
7    마포구  219.0  202.0  183.0  221.0
8    노원구  139.0  153.0  165.0  189.0
9   영등포구  263.0  303.0  326.0  330.0
10   강서구  209.0  260.0  279.0  282.0
11   성북구  121.0  148.0  165.0  180.0
12   성동구  108.0  123.0  126.0  144.0
13   종로구   87.0   94.0   84.0   85.0
14    중구  198.0  215.0  213.0  212.0
15   은평구  135.0  126.0  148.0  166.0
16   강북구   90.0  107.0  122.0  132.0
17   강동구  220.0  254.0  268.0  280.0
18   구로구  156.0  184.0  207.0  229.0
19   양천구  147.0  174.0  186.0  198.0
20   관악구  250.0  278.0  265.0  285.0
21   금천구  133.0  162.0  173.0  203.0
22   도봉구  113.0  129.0  137.0  149.0
23   중랑구  144.0  186.0  196.0  223.0
24  서대문구  124.0  160.0  191.0  201.0

In [37]:
conve_long = pd.melt(conve, id_vars=['자치구별'], var_name='계약연도', value_name='편의점수')
conve_long

    자치구별  계약연도   편의점수
0    서초구  2018  298.0
1    강남구  2018  558.0
2    동작구  2018  118.0
3    송파구  2018  108.0
4    광진구  2018  137.0
..   ...   ...    ...
95   관악구  2021  285.0
96   금천구  2021  203.0
97   도봉구  2021  149.0
98   중랑구  2021  223.0
99  서대문구  2021  201.0

[100 rows x 3 columns]

### 카페

In [38]:
cafe = pd.read_csv('C:/acorn/MidtermProject/프로젝트/팀원들 자료 정리/연도별 서울 카페수.csv', index_col=0)
cafe.drop(index=25, inplace=True)
del cafe['2022카페수']
cafe.rename(columns={'2018카페수':'2018', '2019카페수':'2019', '2020카페수':'2020', '2021카페수':'2021'}, inplace=True)
cafe

    자치구별    2018    2019    2020    2021
0    구로구   407.0   414.0   459.0   474.0
1    서초구   949.0   974.0  1005.0  1004.0
2   영등포구   799.0   844.0   864.0   916.0
3   서대문구   492.0   525.0   522.0   496.0
4    강남구  1679.0  1794.0  1834.0  1873.0
5     중구  1072.0  1135.0  1149.0  1148.0
6    송파구   445.0   476.0   585.0   692.0
7    종로구   877.0   896.0   862.0   850.0
8    마포구   943.0   851.0   755.0   906.0
9    성북구   433.0   455.0   492.0   524.0
10  동대문구   395.0   408.0   424.0   427.0
11   용산구   391.0   422.0   444.0   449.0
12   중랑구   247.0   296.0   329.0   367.0
13   강북구   211.0   221.0   243.0   251.0
14   동작구   416.0   439.0   432.0   453.0
15   은평구   387.0   368.0   400.0   408.0
16   강서구   748.0   842.0   907.0   984.0
17   강동구   416.0   471.0   517.0   579.0
18   도봉구   229.0   249.0   273.0   281.0
19   금천구   324.0   339.0   375.0   400.0
20   양천구   357.0   392.0   415.0   425.0
21   관악구   479.0   527.0   559.0   593.0
22   노원구   433.0   475.0   484.0   523.0
23   광진구   374.0   443.0   503.0   551.0
24   성동구   344.0   383.0   422.0   437.0

In [39]:
cafe_long = pd.melt(cafe, id_vars=['자치구별'], var_name='계약연도', value_name='카페수')
cafe_long

    자치구별  계약연도     카페수
0    구로구  2018   407.0
1    서초구  2018   949.0
2   영등포구  2018   799.0
3   서대문구  2018   492.0
4    강남구  2018  1679.0
..   ...   ...     ...
95   양천구  2021   425.0
96   관악구  2021   593.0
97   노원구  2021   523.0
98   광진구  2021   551.0
99   성동구  2021   437.0

[100 rows x 3 columns]

### 초중고

In [43]:
school = pd.read_csv('C:/acorn/midproject/analysis/year_school_long.csv', index_col=0)
school

     계약연도 자치구별  학교수
0    2018  강남구  101
1    2018  강동구   73
2    2018  강북구   41
3    2018  강서구  104
4    2018  관악구   72
..    ...  ...  ...
120  2022  용산구   44
121  2022  은평구   84
122  2022  종로구   50
123  2022   중구   42
124  2022  중랑구   58

[125 rows x 3 columns]

In [44]:
school = school[school['계약연도'] != 2022]
school

    계약연도 자치구별  학교수
0   2018  강남구  101
1   2018  강동구   73
2   2018  강북구   41
3   2018  강서구  104
4   2018  관악구   72
..   ...  ...  ...
95  2021  용산구   44
96  2021  은평구   84
97  2021  종로구   50
98  2021   중구   42
99  2021  중랑구   57

[100 rows x 3 columns]

### 병원

In [45]:
hos = pd.read_csv('C:/acorn/MidtermProject/프로젝트/maenuk/전처리 완/18-21병원수.csv', index_col=0)
hos.rename(columns={'2018년도병원수':'2018', '2019년도병원수':'2019', '2020년도병원수':'2020', '2021년도병원수':'2021'}, inplace=True)
hos

    자치구별  2018  2019  2020  2021
3    종로구   496   494   494   489
4     중구   558   560   572   572
5    용산구   304   307   310   323
6    성동구   432   444   456   460
7    광진구   553   552   552   559
8   동대문구   603   607   586   596
9    중랑구   498   511   531   535
10   성북구   530   528   540   533
11   강북구   450   461   466   467
12   도봉구   364   369   367   366
13   노원구   717   725   734   737
14   은평구   644   662   677   688
15  서대문구   430   435   441   437
16   마포구   715   730   742   762
17   양천구   627   626   638   651
18   강서구   802   836   861   887
19   구로구   556   559   569   583
20   금천구   339   356   354   356
21  영등포구   738   756   779   793
22   동작구   570   576   588   595
23   관악구   681   693   698   710
24   서초구  1201  1226  1251  1306
25   강남구  2594  2643  2693  2790
26   송파구  1129  1165  1194  1214
27   강동구   771   789   823   852

In [46]:
hos_long = pd.melt(hos, id_vars=['자치구별'], var_name='계약연도', value_name='병원수')
hos_long

   자치구별  계약연도   병원수
0   종로구  2018   496
1    중구  2018   558
2   용산구  2018   304
3   성동구  2018   432
4   광진구  2018   553
..  ...   ...   ...
95  관악구  2021   710
96  서초구  2021  1306
97  강남구  2021  2790
98  송파구  2021  1214
99  강동구  2021   852

[100 rows x 3 columns]

### 학원

In [47]:
aca = pd.read_csv('C:/acorn/MidtermProject/프로젝트/maenuk/전처리 완/18-21학원수.csv', index_col=0)
aca = aca.reset_index()
aca.rename(columns={'2018학원수':'2018', '2019학원수':'2019', '2020학원수':'2020', '2021학원수':'2021'}, inplace=True)
aca

    자치구별  2018  2019  2020  2021
0    종로구   274   259   243   217
1     중구   119   118   109    91
2    용산구   158   155   154   137
3    성동구   314   293   289   290
4    광진구   430   406   405   426
5   동대문구   363   368   350   359
6    중랑구   273   276   262   257
7    성북구   464   450   439   451
8    강북구   218   209   206   210
9    도봉구   335   317   297   285
10   노원구   747   740   718   684
11   은평구   521   525   519   509
12  서대문구   345   346   348   342
13   마포구   644   683   689   692
14   양천구  1062  1037  1008   979
15   강서구   707   693   694   697
16   구로구   427   406   394   386
17   금천구   222   224   212   208
18  영등포구   467   446   445   440
19   동작구   458   465   471   487
20   관악구   450   443   431   434
21   서초구  1130  1119  1148  1146
22   강남구  2263  2279  2361  2383
23   송파구  1051  1115  1076  1045
24   강동구   638   672   724   654

In [48]:
aca_long = pd.melt(aca, id_vars=['자치구별'], var_name='계약연도', value_name='학원수')
aca_long

   자치구별  계약연도   학원수
0   종로구  2018   274
1    중구  2018   119
2   용산구  2018   158
3   성동구  2018   314
4   광진구  2018   430
..  ...   ...   ...
95  관악구  2021   434
96  서초구  2021  1146
97  강남구  2021  2383
98  송파구  2021  1045
99  강동구  2021   654

[100 rows x 3 columns]

### 대학교

In [49]:
uni = pd.read_csv('C:/acorn/MidtermProject/프로젝트/maenuk/전처리 완/18-22대학수.csv', index_col=0)
uni = uni.reset_index()
del uni['2022년도대학교수']
uni.rename(columns={'2018년도대학교수':'2018', '2019년도대학교수':'2019', '2020년도대학교수':'2020', '2021년도대학교수':'2021'}, inplace=True)
uni

    자치구별  2018  2019  2020  2021
0    종로구     3     3     3     3
1     중구     2     2     2     2
2    용산구     1     1     1     1
3    성동구     2     2     2     2
4    광진구     3     3     3     3
5   동대문구     4     4     4     4
6    중랑구     1     1     1     1
7    성북구     6     6     6     6
8    도봉구     1     1     1     1
9    노원구     6     6     6     6
10   은평구     1     1     1     1
11  서대문구     6     6     6     6
12   마포구     2     2     2     2
13   강서구     1     1     1     1
14   구로구     3     3     3     3
15   동작구     3     3     3     3
16   관악구     1     1     1     1
17   서초구     1     1     1     1
18   송파구     1     1     1     1

In [50]:
uni_long = pd.melt(uni, id_vars=['자치구별'], var_name='계약연도', value_name='대학교수')
uni_long

   자치구별  계약연도  대학교수
0   종로구  2018     3
1    중구  2018     2
2   용산구  2018     1
3   성동구  2018     2
4   광진구  2018     3
..  ...   ...   ...
71  구로구  2021     3
72  동작구  2021     3
73  관악구  2021     1
74  서초구  2021     1
75  송파구  2021     1

[76 rows x 3 columns]

In [52]:
crime_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구별    100 non-null    object
 1   계약연도    100 non-null    object
 2   범죄건수    100 non-null    int64
dtypes: int64(1), object(2)
memory usage: 2.5+ KB

In [64]:
bus_long.info()
bus_long['정류장수'] = bus_long['정류장수'].astype('int64')
bus_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구별    100 non-null    object
 1   계약연도    100 non-null    object
 2   정류장수    100 non-null    int32
dtypes: int32(1), object(2)
memory usage: 2.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구별    100 non-null    object
 1   계약연도    100 non-null    object
 2   정류장수    100 non-null    int64
dtypes: int64(1), object(2)
memory usage: 2.5+ KB

In [65]:
#school.info()
school['계약연도'] = school['계약연도'].astype('str')
school.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   계약연도    100 non-null    object
 1   자치구별    100 non-null    object
 2   학교수     100 non-null    int64
dtypes: int64(1), object(2)
memory usage: 3.1+ KB

C:\Users\khg08\AppData\Local\Temp\ipykernel_3104\22803723.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  school['계약연도'] = school['계약연도'].astype('str')

In [67]:
cafe_long.info()
cafe_long['카페수'] = cafe_long['카페수'].astype('int64')
cafe_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구별    100 non-null    object
 1   계약연도    100 non-null    object
 2   카페수     100 non-null    int64
dtypes: int64(1), object(2)
memory usage: 2.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구별    100 non-null    object
 1   계약연도    100 non-null    object
 2   카페수     100 non-null    int64
dtypes: int64(1), object(2)
memory usage: 2.5+ KB

In [68]:
conve_long.info()
conve_long['편의점수'] = conve_long['편의점수'].astype('int64')
conve_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구별    100 non-null    object
 1   계약연도    100 non-null    object
 2   편의점수    100 non-null    float64
dtypes: float64(1), object(2)
memory usage: 2.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   자치구별    100 non-null    object
 1   계약연도    100 non-null    object
 2   편의점수    100 non-null    int64
dtypes: int64(1), object(2)
memory usage: 2.5+ KB

In [71]:
from functools import reduce
import pandas as pd
dfs = [crime_long, bus_long, conve_long, cafe_long, school, hos_long, aca_long, uni_long]
df = reduce(lambda left, right: pd.merge(left, right, on=['자치구별', '계약연도'], how='outer'), dfs)
df

   자치구별  계약연도  범죄건수  정류장수  편의점수   카페수  학교수   병원수   학원수  대학교수
0   종로구  2018   364   382    87   877   50   496   274   3.0
1    중구  2018   357   207   198  1072   42   558   119   2.0
2   용산구  2018   417   349   105   391   44   304   158   1.0
3   성동구  2018   204   439   108   344   50   432   314   2.0
4   광진구  2018   363   286   137   374   52   553   430   3.0
..  ...   ...   ...   ...   ...   ...  ...   ...   ...   ...
95  관악구  2021   528   467   285   593   72   710   434   1.0
96  서초구  2021   540   605   317  1004   62  1306  1146   1.0
97  강남구  2021   946   520   615  1873  101  2790  2383   NaN
98  송파구  2021   496   414   208   692  106  1214  1045   1.0
99  강동구  2021   234   365   280   579   76   852   654   NaN

[100 rows x 10 columns]

# 매매가

In [85]:
buy2018 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_buysell_price_2018-22/save_point3_apt_buysell_2018_data.csv')
buy2018.drop(index=25, inplace=True)
buy2018.rename(columns={'1m^2 전용면적당 거래금액(만원)':'매매가'}, inplace=True)
buy2018 = buy2018[['자치구별', '매매가']]
buy2018['계약연도'] = '2018'
buy2018

    자치구별     매매가  계약연도
0    강남구  1702.0  2018
1    강동구   858.0  2018
2    강북구   563.0  2018
3    강서구   728.0  2018
4    관악구   642.0  2018
5    광진구   943.0  2018
6    구로구   595.0  2018
7    금천구   516.0  2018
8    노원구   601.0  2018
9    도봉구   504.0  2018
10  동대문구   693.0  2018
11   동작구   880.0  2018
12   마포구   989.0  2018
13  서대문구   727.0  2018
14   서초구  1461.0  2018
15   성동구  1048.0  2018
16   성북구   629.0  2018
17   송파구  1201.0  2018
18   양천구   811.0  2018
19  영등포구   845.0  2018
20   용산구  1200.0  2018
21   은평구   627.0  2018
22   종로구   764.0  2018
23    중구   871.0  2018
24   중랑구   541.0  2018

In [84]:
buy2019 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_buysell_price_2018-22/save_point3_apt_buysell_2019_data.csv')
buy2019.drop(index=25, inplace=True)
buy2019.rename(columns={'1m^2 전용면적당 거래금액(만원)':'매매가'}, inplace=True)
buy2019 = buy2019[['자치구별', '매매가']]
buy2019['계약연도'] = '2019'
buy2019

    자치구별     매매가  계약연도
0    강남구  2051.0  2019
1    강동구  1007.0  2019
2    강북구   665.0  2019
3    강서구   852.0  2019
4    관악구   757.0  2019
5    광진구  1105.0  2019
6    구로구   707.0  2019
7    금천구   619.0  2019
8    노원구   703.0  2019
9    도봉구   594.0  2019
10  동대문구   840.0  2019
11   동작구  1066.0  2019
12   마포구  1221.0  2019
13  서대문구   922.0  2019
14   서초구  1755.0  2019
15   성동구  1245.0  2019
16   성북구   771.0  2019
17   송파구  1440.0  2019
18   양천구  1038.0  2019
19  영등포구  1039.0  2019
20   용산구  1463.0  2019
21   은평구   729.0  2019
22   종로구  1015.0  2019
23    중구  1024.0  2019
24   중랑구   660.0  2019

In [86]:
buy2020 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_buysell_price_2018-22/save_point3_apt_buysell_2020_data.csv')
buy2020.drop(index=25, inplace=True)
buy2020.rename(columns={'1m^2 전용면적당 거래금액(만원)':'매매가'}, inplace=True)
buy2020 = buy2020[['자치구별', '매매가']]
buy2020['계약연도'] = '2020'
buy2020

    자치구별     매매가  계약연도
0    강남구  2117.0  2020
1    강동구  1170.0  2020
2    강북구   771.0  2020
3    강서구   964.0  2020
4    관악구   871.0  2020
5    광진구  1291.0  2020
6    구로구   769.0  2020
7    금천구   739.0  2020
8    노원구   844.0  2020
9    도봉구   675.0  2020
10  동대문구   995.0  2020
11   동작구  1230.0  2020
12   마포구  1344.0  2020
13  서대문구  1038.0  2020
14   서초구  1913.0  2020
15   성동구  1471.0  2020
16   성북구   914.0  2020
17   송파구  1601.0  2020
18   양천구  1143.0  2020
19  영등포구  1180.0  2020
20   용산구  1594.0  2020
21   은평구   827.0  2020
22   종로구  1034.0  2020
23    중구  1138.0  2020
24   중랑구   760.0  2020

In [87]:
buy2021 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_buysell_price_2018-22/save_point3_apt_buysell_2021_data.csv')
buy2021.drop(index=25, inplace=True)
buy2021.rename(columns={'1m^2 전용면적당 거래금액(만원)':'매매가'}, inplace=True)
buy2021 = buy2021[['자치구별', '매매가']]
buy2021['계약연도'] = '2021'
buy2021

    자치구별     매매가  계약연도
0    강남구  2351.0  2021
1    강동구  1437.0  2021
2    강북구   939.0  2021
3    강서구  1175.0  2021
4    관악구  1089.0  2021
5    광진구  1517.0  2021
6    구로구   945.0  2021
7    금천구   914.0  2021
8    노원구  1116.0  2021
9    도봉구   899.0  2021
10  동대문구  1174.0  2021
11   동작구  1670.0  2021
12   마포구  1568.0  2021
13  서대문구  1256.0  2021
14   서초구  2208.0  2021
15   성동구  1806.0  2021
16   성북구  1144.0  2021
17   송파구  1983.0  2021
18   양천구  1353.0  2021
19  영등포구  1378.0  2021
20   용산구  1903.0  2021
21   은평구  1042.0  2021
22   종로구  1239.0  2021
23    중구  1285.0  2021
24   중랑구   969.0  2021

In [91]:
price = pd.concat([buy2018, buy2019, buy2020, buy2021])
price

   자치구별     매매가  계약연도
0   강남구  1702.0  2018
1   강동구   858.0  2018
2   강북구   563.0  2018
3   강서구   728.0  2018
4   관악구   642.0  2018
..  ...     ...   ...
20  용산구  1903.0  2021
21  은평구  1042.0  2021
22  종로구  1239.0  2021
23   중구  1285.0  2021
24  중랑구   969.0  2021

[100 rows x 3 columns]

# 전월세가

In [92]:
buy2018 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2018_data.csv')
buy2018.drop(index=25, inplace=True)
buy2018.rename(columns={'1m^2 전용면적당 거래금액(만원)':'전월세가'}, inplace=True)
buy2018 = buy2018[['자치구별', '전월세가']]
buy2018['계약연도'] = '2018'
buy2018

    자치구별   전월세가  계약연도
0    강남구  654.0  2018
1    강동구  472.0  2018
2    강북구  336.0  2018
3    강서구  406.0  2018
4    관악구  369.0  2018
5    광진구  538.0  2018
6    구로구  360.0  2018
7    금천구  335.0  2018
8    노원구  297.0  2018
9    도봉구  276.0  2018
10  동대문구  408.0  2018
11   동작구  502.0  2018
12   마포구  512.0  2018
13  서대문구  436.0  2018
14   서초구  645.0  2018
15   성동구  542.0  2018
16   성북구  407.0  2018
17   송파구  577.0  2018
18   양천구  494.0  2018
19  영등포구  445.0  2018
20   용산구  508.0  2018
21   은평구  369.0  2018
22   종로구  419.0  2018
23    중구  482.0  2018
24   중랑구  305.0  2018

In [93]:
buy2019 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2019_data.csv')
buy2019.drop(index=25, inplace=True)
buy2019.rename(columns={'1m^2 전용면적당 거래금액(만원)':'전월세가'}, inplace=True)
buy2019 = buy2019[['자치구별', '전월세가']]
buy2019['계약연도'] = '2019'
buy2019

    자치구별   전월세가  계약연도
0    강남구  676.0  2019
1    강동구  471.0  2019
2    강북구  339.0  2019
3    강서구  442.0  2019
4    관악구  380.0  2019
5    광진구  546.0  2019
6    구로구  362.0  2019
7    금천구  346.0  2019
8    노원구  304.0  2019
9    도봉구  282.0  2019
10  동대문구  423.0  2019
11   동작구  499.0  2019
12   마포구  536.0  2019
13  서대문구  463.0  2019
14   서초구  638.0  2019
15   성동구  558.0  2019
16   성북구  415.0  2019
17   송파구  576.0  2019
18   양천구  483.0  2019
19  영등포구  478.0  2019
20   용산구  532.0  2019
21   은평구  395.0  2019
22   종로구  538.0  2019
23    중구  453.0  2019
24   중랑구  370.0  2019

In [94]:
buy2020 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2020_data.csv')
buy2020.drop(index=25, inplace=True)
buy2020.rename(columns={'1m^2 전용면적당 거래금액(만원)':'전월세가'}, inplace=True)
buy2020 = buy2020[['자치구별', '전월세가']]
buy2020['계약연도'] = '2020'
buy2020

    자치구별   전월세가  계약연도
0    강남구  781.0  2020
1    강동구  515.0  2020
2    강북구  394.0  2020
3    강서구  453.0  2020
4    관악구  411.0  2020
5    광진구  604.0  2020
6    구로구  375.0  2020
7    금천구  412.0  2020
8    노원구  332.0  2020
9    도봉구  314.0  2020
10  동대문구  474.0  2020
11   동작구  569.0  2020
12   마포구  519.0  2020
13  서대문구  499.0  2020
14   서초구  760.0  2020
15   성동구  618.0  2020
16   성북구  462.0  2020
17   송파구  647.0  2020
18   양천구  527.0  2020
19  영등포구  506.0  2020
20   용산구  579.0  2020
21   은평구  439.0  2020
22   종로구  479.0  2020
23    중구  549.0  2020
24   중랑구  391.0  2020

In [95]:
buy2021 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2021_data.csv')
buy2021.drop(index=25, inplace=True)
buy2021.rename(columns={'1m^2 전용면적당 거래금액(만원)':'전월세가'}, inplace=True)
buy2021 = buy2021[['자치구별', '전월세가']]
buy2021['계약연도'] = '2021'
buy2021

    자치구별   전월세가  계약연도
0    강남구  824.0  2021
1    강동구  516.0  2021
2    강북구  393.0  2021
3    강서구  470.0  2021
4    관악구  460.0  2021
5    광진구  667.0  2021
6    구로구  364.0  2021
7    금천구  403.0  2021
8    노원구  368.0  2021
9    도봉구  355.0  2021
10  동대문구  513.0  2021
11   동작구  630.0  2021
12   마포구  585.0  2021
13  서대문구  533.0  2021
14   서초구  796.0  2021
15   성동구  658.0  2021
16   성북구  497.0  2021
17   송파구  672.0  2021
18   양천구  535.0  2021
19  영등포구  554.0  2021
20   용산구  623.0  2021
21   은평구  444.0  2021
22   종로구  568.0  2021
23    중구  566.0  2021
24   중랑구  419.0  2021

In [96]:
rentprice = pd.concat([buy2018, buy2019, buy2020, buy2021])
rentprice

   자치구별   전월세가  계약연도
0   강남구  654.0  2018
1   강동구  472.0  2018
2   강북구  336.0  2018
3   강서구  406.0  2018
4   관악구  369.0  2018
..  ...    ...   ...
20  용산구  623.0  2021
21  은평구  444.0  2021
22  종로구  568.0  2021
23   중구  566.0  2021
24  중랑구  419.0  2021

[100 rows x 3 columns]

In [97]:
from functools import reduce
import pandas as pd
dfs = [df, price, rentprice]
final = reduce(lambda left, right: pd.merge(left, right, on=['자치구별', '계약연도']), dfs)
final

   자치구별  계약연도  범죄건수  정류장수  편의점수   카페수  학교수   병원수   학원수  대학교수     매매가   전월세가
0   종로구  2018   364   382    87   877   50   496   274   3.0   764.0  419.0
1    중구  2018   357   207   198  1072   42   558   119   2.0   871.0  482.0
2   용산구  2018   417   349   105   391   44   304   158   1.0  1200.0  508.0
3   성동구  2018   204   439   108   344   50   432   314   2.0  1048.0  542.0
4   광진구  2018   363   286   137   374   52   553   430   3.0   943.0  538.0
..  ...   ...   ...   ...   ...   ...  ...   ...   ...   ...     ...    ...
95  관악구  2021   528   467   285   593   72   710   434   1.0  1089.0  460.0
96  서초구  2021   540   605   317  1004   62  1306  1146   1.0  2208.0  796.0
97  강남구  2021   946   520   615  1873  101  2790  2383   NaN  2351.0  824.0
98  송파구  2021   496   414   208   692  106  1214  1045   1.0  1983.0  672.0
99  강동구  2021   234   365   280   579   76   852   654   NaN  1437.0  516.0

[100 rows x 12 columns]

In [98]:
final.to_csv('인프라모든요인.csv')

In [103]:
final[final['계약연도'] == '2021'].to_csv('인프라모든요인2021.csv')

### 변동률

In [12]:
df = pd.read_csv('C:/acorn/midproject/analysis/인프라모든요인.csv', index_col=0)
df

   자치구별  계약연도  범죄건수  정류장수  편의점수   카페수  학교수   병원수   학원수  대학교수     매매가   전월세가
0   종로구  2018   364   382    87   877   50   496   274   3.0   764.0  419.0
1    중구  2018   357   207   198  1072   42   558   119   2.0   871.0  482.0
2   용산구  2018   417   349   105   391   44   304   158   1.0  1200.0  508.0
3   성동구  2018   204   439   108   344   50   432   314   2.0  1048.0  542.0
4   광진구  2018   363   286   137   374   52   553   430   3.0   943.0  538.0
..  ...   ...   ...   ...   ...   ...  ...   ...   ...   ...     ...    ...
95  관악구  2021   528   467   285   593   72   710   434   1.0  1089.0  460.0
96  서초구  2021   540   605   317  1004   62  1306  1146   1.0  2208.0  796.0
97  강남구  2021   946   520   615  1873  101  2790  2383   0.0  2351.0  824.0
98  송파구  2021   496   414   208   692  106  1214  1045   1.0  1983.0  672.0
99  강동구  2021   234   365   280   579   76   852   654   0.0  1437.0  516.0

[100 rows x 12 columns]

In [14]:
df1 = df[df['계약연도']==2018]
df2 = df[df['계약연도']==2021]
df2

    자치구별  계약연도  범죄건수  정류장수  편의점수   카페수  학교수   병원수   학원수  대학교수     매매가   전월세가
75   종로구  2021   271   369    85   850   50   489   217   3.0  1239.0  568.0
76    중구  2021   282   200   212  1148   42   572    91   2.0  1285.0  566.0
77   용산구  2021   248   328   130   449   44   323   137   1.0  1903.0  623.0
78   성동구  2021   220   445   144   437   50   460   290   2.0  1806.0  658.0
79   광진구  2021   325   270   220   551   52   559   426   3.0  1517.0  667.0
80  동대문구  2021   282   303   204   427   58   596   359   4.0  1174.0  513.0
81   중랑구  2021   273   380   223   367   57   535   257   1.0   969.0  419.0
82   성북구  2021   222   601   180   524   73   533   451   6.0  1144.0  497.0
83   강북구  2021   222   409   132   251   41   467   210   0.0   939.0  393.0
84   도봉구  2021   131   358   149   281   56   366   285   1.0   899.0  355.0
85   노원구  2021   293   527   189   523  118   737   684   6.0  1116.0  368.0
86   은평구  2021   293   497   166   408   84   688   509   1.0  1042.0  444.0
87  서대문구  2021   292   454   201   496   47   437   342   6.0  1256.0  533.0
88   마포구  2021   524   563   221   906   54   762   692   2.0  1568.0  585.0
89   양천구  2021   202   317   198   425   79   651   979   0.0  1353.0  535.0
90   강서구  2021   434   569   282   984  103   887   697   1.0  1175.0  470.0
91   구로구  2021   341   497   229   474   68   583   386   3.0   945.0  364.0
92   금천구  2021   246   342   203   400   39   356   208   0.0   914.0  403.0
93  영등포구  2021   480   466   330   916   53   793   440   0.0  1378.0  554.0
94   동작구  2021   304   437   161   453   51   595   487   3.0  1670.0  630.0
95   관악구  2021   528   467   285   593   72   710   434   1.0  1089.0  460.0
96   서초구  2021   540   605   317  1004   62  1306  1146   1.0  2208.0  796.0
97   강남구  2021   946   520   615  1873  101  2790  2383   0.0  2351.0  824.0
98   송파구  2021   496   414   208   692  106  1214  1045   1.0  1983.0  672.0
99   강동구  2021   234   365   280   579   76   852   654   0.0  1437.0  516.0

In [15]:
df=pd.merge(df1, df2, on='자치구별')
df

,자치구별,계약연도_x,범죄건수_x,정류장수_x,편의점수_x,카페수_x,학교수_x,병원수_x,학원수_x,대학교수_x,...,범죄건수_y,정류장수_y,편의점수_y,카페수_y,학교수_y,병원수_y,학원수_y,대학교수_y,매매가_y,전월세가_y
0,종로구,2018,364,382,87,877,50,496,274,3.0,...,271,369,85,850,50,489,217,3.0,1239.0,568.0
1,중구,2018,357,207,198,1072,42,558,119,2.0,...,282,200,212,1148,42,572,91,2.0,1285.0,566.0
2,용산구,2018,417,349,105,391,44,304,158,1.0,...,248,328,130,449,44,323,137,1.0,1903.0,623.0
3,성동구,2018,204,439,108,344,50,432,314,2.0,...,220,445,144,437,50,460,290,2.0,1806.0,658.0
4,광진구,2018,363,286,137,374,52,553,430,3.0,...,325,270,220,551,52,559,426,3.0,1517.0,667.0
5,동대문구,2018,243,318,154,395,58,603,363,4.0,...,282,303,204,427,58,596,359,4.0,1174.0,513.0
6,중랑구,2018,238,379,144,247,57,498,273,1.0,...,273,380,223,367,57,535,257,1.0,969.0,419.0
7,성북구,2018,303,611,121,433,73,530,464,6.0,...,222,601,180,524,73,533,451,6.0,1144.0,497.0
8,강북구,2018,273,460,90,211,41,450,218,0.0,...,222,409,132,251,41,467,210,0.0,939.0,393.0
9,도봉구,2018,177,386,113,229,56,364,335,1.0,...,131,358,149,281,56,366,285,1.0,899.0,355.0
10,노원구,2018,293,537,139,433,118,717,747,6.0,...,293,527,189,523,118,737,684,6.0,1116.0,368.0
11,은평구,2018,312,499,135,387,84,644,521,1.0,...,293,497,166,408,84,688,509,1.0,1042.0,444.0
12,서대문구,2018,278,444,124,492,47,430,345,6.0,...,292,454,201,496,47,437,342,6.0,1256.0,533.0
13,마포구,2018,735,569,219,943,54,715,644,2.0,...,524,563,221,906,54,762,692,2.0,1568.0,585.0
14,양천구,2018,193,363,147,357,79,627,1062,0.0,...,202,317,198,425,79,651,979,0.0,1353.0,535.0
15,강서구,2018,424,576,209,748,104,802,707,1.0,...,434,569,282,984,103,887,697,1.0,1175.0,470.0
16,구로구,2018,405,478,156,407,65,556,427,3.0,...,341,497,229,474,68,583,386,3.0,945.0,364.0
17,금천구,2018,273,342,133,324,39,339,222,0.0,...,246,342,203,400,39,356,208,0.0,914.0,403.0
18,영등포구,2018,592,491,263,799,52,738,467,0.0,...,480,466,330,916,53,793,440,0.0,1378.0,554.0
19,동작구,2018,416,460,118,416,51,570,458,3.0,...,304,437,161,453,51,595,487,3.0,1670.0,630.0
20,관악구,2018,545,485,250,479,72,681,450,1.0,...,528,467,285,593,72,710,434,1.0,1089.0,460.0
21,서초구,2018,635,648,298,949,62,1201,1130,1.0,...,540,605,317,1004,62,1306,1146,1.0,2208.0,796.0
22,강남구,2018,1010,534,558,1679,101,2594,2263,0.0,...,946,520,615,1873,101,2790,2383,0.0,2351.0,824.0
23,송파구,2018,515,413,108,445,104,1129,1051,1.0,...,496,414,208,692,106,1214,1045,1.0,1983.0,672.0
24,강동구,2018,241,349,220,416,73,771,638,0.0,...,234,365,280,579,76,852,654,0.0,1437.0,516.0

In [17]:
df['범죄건수변동률'] = ((df['범죄건수_y'] - df['범죄건수_x']) / df['범죄건수_x']) * 100
df['정류장수변동률'] = ((df['정류장수_y'] - df['정류장수_x']) / df['정류장수_x']) * 100
df['편의점수변동률'] = ((df['편의점수_y'] - df['편의점수_x']) / df['편의점수_x']) * 100
df['카페수변동률'] = ((df['카페수_y'] - df['카페수_x']) / df['카페수_x']) * 100
df['학교수변동률'] = ((df['학교수_y'] - df['학교수_x']) / df['학교수_x']) * 100
df['병원수변동률'] = ((df['병원수_y'] - df['병원수_x']) / df['병원수_x']) * 100
df['학원수변동률'] = ((df['학원수_y'] - df['학원수_x']) / df['학원수_x']) * 100
df['대학교수변동률'] = ((df['대학교수_y'] - df['대학교수_x']) / df['대학교수_x']) * 100
df['매매가변동률'] = ((df['매매가_y'] - df['매매가_x']) / df['매매가_x']) * 100
df['전월세가변동률'] = ((df['전월세가_y'] - df['전월세가_x']) / df['전월세가_x']) * 100
df

,자치구별,계약연도_x,범죄건수_x,정류장수_x,편의점수_x,카페수_x,학교수_x,병원수_x,학원수_x,대학교수_x,...,범죄건수변동률,정류장수변동률,편의점수변동률,카페수변동률,학교수변동률,병원수변동률,학원수변동률,대학교수변동률,매매가변동률,전월세가변동률
0,종로구,2018,364,382,87,877,50,496,274,3.0,...,-25.549451,-3.403141,-2.298851,-3.078677,0.000000,-1.411290,-20.802920,0.0,62.172775,35.560859
1,중구,2018,357,207,198,1072,42,558,119,2.0,...,-21.008403,-3.381643,7.070707,7.089552,0.000000,2.508961,-23.529412,0.0,47.531573,17.427386
2,용산구,2018,417,349,105,391,44,304,158,1.0,...,-40.527578,-6.017192,23.809524,14.833760,0.000000,6.250000,-13.291139,0.0,58.583333,22.637795
3,성동구,2018,204,439,108,344,50,432,314,2.0,...,7.843137,1.366743,33.333333,27.034884,0.000000,6.481481,-7.643312,0.0,72.328244,21.402214
4,광진구,2018,363,286,137,374,52,553,430,3.0,...,-10.468320,-5.594406,60.583942,47.326203,0.000000,1.084991,-0.930233,0.0,60.869565,23.977695
5,동대문구,2018,243,318,154,395,58,603,363,4.0,...,16.049383,-4.716981,32.467532,8.101266,0.000000,-1.160862,-1.101928,0.0,69.408369,25.735294
6,중랑구,2018,238,379,144,247,57,498,273,1.0,...,14.705882,0.263852,54.861111,48.582996,0.000000,7.429719,-5.860806,0.0,79.112754,37.377049
7,성북구,2018,303,611,121,433,73,530,464,6.0,...,-26.732673,-1.636661,48.760331,21.016166,0.000000,0.566038,-2.801724,0.0,81.875994,22.113022
8,강북구,2018,273,460,90,211,41,450,218,0.0,...,-18.681319,-11.086957,46.666667,18.957346,0.000000,3.777778,-3.669725,NaN,66.785080,16.964286
9,도봉구,2018,177,386,113,229,56,364,335,1.0,...,-25.988701,-7.253886,31.858407,22.707424,0.000000,0.549451,-14.925373,0.0,78.373016,28.623188
10,노원구,2018,293,537,139,433,118,717,747,6.0,...,0.000000,-1.862197,35.971223,20.785219,0.000000,2.789400,-8.433735,0.0,85.690516,23.905724
11,은평구,2018,312,499,135,387,84,644,521,1.0,...,-6.089744,-0.400802,22.962963,5.426357,0.000000,6.832298,-2.303263,0.0,66.188198,20.325203
12,서대문구,2018,278,444,124,492,47,430,345,6.0,...,5.035971,2.252252,62.096774,0.813008,0.000000,1.627907,-0.869565,0.0,72.764787,22.247706
13,마포구,2018,735,569,219,943,54,715,644,2.0,...,-28.707483,-1.054482,0.913242,-3.923648,0.000000,6.573427,7.453416,0.0,58.543984,14.257812
14,양천구,2018,193,363,147,357,79,627,1062,0.0,...,4.663212,-12.672176,34.693878,19.047619,0.000000,3.827751,-7.815443,NaN,66.831073,8.299595
15,강서구,2018,424,576,209,748,104,802,707,1.0,...,2.358491,-1.215278,34.928230,31.550802,-0.961538,10.598504,-1.414427,0.0,61.401099,15.763547
16,구로구,2018,405,478,156,407,65,556,427,3.0,...,-15.802469,3.974895,46.794872,16.461916,4.615385,4.856115,-9.601874,0.0,58.823529,1.111111
17,금천구,2018,273,342,133,324,39,339,222,0.0,...,-9.890110,0.000000,52.631579,23.456790,0.000000,5.014749,-6.306306,NaN,77.131783,20.298507
18,영등포구,2018,592,491,263,799,52,738,467,0.0,...,-18.918919,-5.091650,25.475285,14.643304,1.923077,7.452575,-5.781585,NaN,63.076923,24.494382
19,동작구,2018,416,460,118,416,51,570,458,3.0,...,-26.923077,-5.000000,36.440678,8.894231,0.000000,4.385965,6.331878,0.0,89.772727,25.498008
20,관악구,2018,545,485,250,479,72,681,450,1.0,...,-3.119266,-3.711340,14.000000,23.799582,0.000000,4.258443,-3.555556,0.0,69.626168,24.661247
21,서초구,2018,635,648,298,949,62,1201,1130,1.0,...,-14.960630,-6.635802,6.375839,5.795574,0.000000,8.742714,1.415929,0.0,51.129363,23.410853
22,강남구,2018,1010,534,558,1679,101,2594,2263,0.0,...,-6.336634,-2.621723,10.215054,11.554497,0.000000,7.555898,5.302696,NaN,38.131610,25.993884
23,송파구,2018,515,413,108,445,104,1129,1051,1.0,...,-3.689320,0.242131,92.592593,55.505618,1.923077,7.528787,-0.570885,0.0,65.112406,16.464471
24,강동구,2018,241,349,220,416,73,771,638,0.0,...,-2.904564,4.584527,27.272727,39.182692,4.109589,10.505837,2.507837,NaN,67.482517,9.322034

In [18]:
df.columns

Index(['자치구별', '계약연도_x', '범죄건수_x', '정류장수_x', '편의점수_x', '카페수_x', '학교수_x',
       '병원수_x', '학원수_x', '대학교수_x', '매매가_x', '전월세가_x', '계약연도_y', '범죄건수_y',
       '정류장수_y', '편의점수_y', '카페수_y', '학교수_y', '병원수_y', '학원수_y', '대학교수_y',
       '매매가_y', '전월세가_y', '범죄건수변동률', '정류장수변동률', '편의점수변동률', '카페수변동률', '학교수변동률',
       '병원수변동률', '학원수변동률', '대학교수변동률', '매매가변동률', '전월세가변동률'],
      dtype='object')

In [19]:
final = df[['자치구별', '범죄건수변동률', '정류장수변동률', '편의점수변동률', '카페수변동률', '학교수변동률', '병원수변동률', '학원수변동률', '대학교수변동률', '매매가변동률', '전월세가변동률']]

In [20]:
final

,자치구별,범죄건수변동률,정류장수변동률,편의점수변동률,카페수변동률,학교수변동률,병원수변동률,학원수변동률,대학교수변동률,매매가변동률,전월세가변동률
0,종로구,-25.549451,-3.403141,-2.298851,-3.078677,0.000000,-1.411290,-20.802920,0.0,62.172775,35.560859
1,중구,-21.008403,-3.381643,7.070707,7.089552,0.000000,2.508961,-23.529412,0.0,47.531573,17.427386
2,용산구,-40.527578,-6.017192,23.809524,14.833760,0.000000,6.250000,-13.291139,0.0,58.583333,22.637795
3,성동구,7.843137,1.366743,33.333333,27.034884,0.000000,6.481481,-7.643312,0.0,72.328244,21.402214
4,광진구,-10.468320,-5.594406,60.583942,47.326203,0.000000,1.084991,-0.930233,0.0,60.869565,23.977695
5,동대문구,16.049383,-4.716981,32.467532,8.101266,0.000000,-1.160862,-1.101928,0.0,69.408369,25.735294
6,중랑구,14.705882,0.263852,54.861111,48.582996,0.000000,7.429719,-5.860806,0.0,79.112754,37.377049
7,성북구,-26.732673,-1.636661,48.760331,21.016166,0.000000,0.566038,-2.801724,0.0,81.875994,22.113022
8,강북구,-18.681319,-11.086957,46.666667,18.957346,0.000000,3.777778,-3.669725,NaN,66.785080,16.964286
9,도봉구,-25.988701,-7.253886,31.858407,22.707424,0.000000,0.549451,-14.925373,0.0,78.373016,28.623188
10,노원구,0.000000,-1.862197,35.971223,20.785219,0.000000,2.789400,-8.433735,0.0,85.690516,23.905724
11,은평구,-6.089744,-0.400802,22.962963,5.426357,0.000000,6.832298,-2.303263,0.0,66.188198,20.325203
12,서대문구,5.035971,2.252252,62.096774,0.813008,0.000000,1.627907,-0.869565,0.0,72.764787,22.247706
13,마포구,-28.707483,-1.054482,0.913242,-3.923648,0.000000,6.573427,7.453416,0.0,58.543984,14.257812
14,양천구,4.663212,-12.672176,34.693878,19.047619,0.000000,3.827751,-7.815443,NaN,66.831073,8.299595
15,강서구,2.358491,-1.215278,34.928230,31.550802,-0.961538,10.598504,-1.414427,0.0,61.401099,15.763547
16,구로구,-15.802469,3.974895,46.794872,16.461916,4.615385,4.856115,-9.601874,0.0,58.823529,1.111111
17,금천구,-9.890110,0.000000,52.631579,23.456790,0.000000,5.014749,-6.306306,NaN,77.131783,20.298507
18,영등포구,-18.918919,-5.091650,25.475285,14.643304,1.923077,7.452575,-5.781585,NaN,63.076923,24.494382
19,동작구,-26.923077,-5.000000,36.440678,8.894231,0.000000,4.385965,6.331878,0.0,89.772727,25.498008
20,관악구,-3.119266,-3.711340,14.000000,23.799582,0.000000,4.258443,-3.555556,0.0,69.626168,24.661247
21,서초구,-14.960630,-6.635802,6.375839,5.795574,0.000000,8.742714,1.415929,0.0,51.129363,23.410853
22,강남구,-6.336634,-2.621723,10.215054,11.554497,0.000000,7.555898,5.302696,NaN,38.131610,25.993884
23,송파구,-3.689320,0.242131,92.592593,55.505618,1.923077,7.528787,-0.570885,0.0,65.112406,16.464471
24,강동구,-2.904564,4.584527,27.272727,39.182692,4.109589,10.505837,2.507837,NaN,67.482517,9.322034

In [21]:
final = final.fillna(0)
final

,자치구별,범죄건수변동률,정류장수변동률,편의점수변동률,카페수변동률,학교수변동률,병원수변동률,학원수변동률,대학교수변동률,매매가변동률,전월세가변동률
0,종로구,-25.549451,-3.403141,-2.298851,-3.078677,0.000000,-1.411290,-20.802920,0.0,62.172775,35.560859
1,중구,-21.008403,-3.381643,7.070707,7.089552,0.000000,2.508961,-23.529412,0.0,47.531573,17.427386
2,용산구,-40.527578,-6.017192,23.809524,14.833760,0.000000,6.250000,-13.291139,0.0,58.583333,22.637795
3,성동구,7.843137,1.366743,33.333333,27.034884,0.000000,6.481481,-7.643312,0.0,72.328244,21.402214
4,광진구,-10.468320,-5.594406,60.583942,47.326203,0.000000,1.084991,-0.930233,0.0,60.869565,23.977695
5,동대문구,16.049383,-4.716981,32.467532,8.101266,0.000000,-1.160862,-1.101928,0.0,69.408369,25.735294
6,중랑구,14.705882,0.263852,54.861111,48.582996,0.000000,7.429719,-5.860806,0.0,79.112754,37.377049
7,성북구,-26.732673,-1.636661,48.760331,21.016166,0.000000,0.566038,-2.801724,0.0,81.875994,22.113022
8,강북구,-18.681319,-11.086957,46.666667,18.957346,0.000000,3.777778,-3.669725,0.0,66.785080,16.964286
9,도봉구,-25.988701,-7.253886,31.858407,22.707424,0.000000,0.549451,-14.925373,0.0,78.373016,28.623188
10,노원구,0.000000,-1.862197,35.971223,20.785219,0.000000,2.789400,-8.433735,0.0,85.690516,23.905724
11,은평구,-6.089744,-0.400802,22.962963,5.426357,0.000000,6.832298,-2.303263,0.0,66.188198,20.325203
12,서대문구,5.035971,2.252252,62.096774,0.813008,0.000000,1.627907,-0.869565,0.0,72.764787,22.247706
13,마포구,-28.707483,-1.054482,0.913242,-3.923648,0.000000,6.573427,7.453416,0.0,58.543984,14.257812
14,양천구,4.663212,-12.672176,34.693878,19.047619,0.000000,3.827751,-7.815443,0.0,66.831073,8.299595
15,강서구,2.358491,-1.215278,34.928230,31.550802,-0.961538,10.598504,-1.414427,0.0,61.401099,15.763547
16,구로구,-15.802469,3.974895,46.794872,16.461916,4.615385,4.856115,-9.601874,0.0,58.823529,1.111111
17,금천구,-9.890110,0.000000,52.631579,23.456790,0.000000,5.014749,-6.306306,0.0,77.131783,20.298507
18,영등포구,-18.918919,-5.091650,25.475285,14.643304,1.923077,7.452575,-5.781585,0.0,63.076923,24.494382
19,동작구,-26.923077,-5.000000,36.440678,8.894231,0.000000,4.385965,6.331878,0.0,89.772727,25.498008
20,관악구,-3.119266,-3.711340,14.000000,23.799582,0.000000,4.258443,-3.555556,0.0,69.626168,24.661247
21,서초구,-14.960630,-6.635802,6.375839,5.795574,0.000000,8.742714,1.415929,0.0,51.129363,23.410853
22,강남구,-6.336634,-2.621723,10.215054,11.554497,0.000000,7.555898,5.302696,0.0,38.131610,25.993884
23,송파구,-3.689320,0.242131,92.592593,55.505618,1.923077,7.528787,-0.570885,0.0,65.112406,16.464471
24,강동구,-2.904564,4.584527,27.272727,39.182692,4.109589,10.505837,2.507837,0.0,67.482517,9.322034

In [22]:
final.to_csv('18대비21_인프라_변동률.csv')