In [1]:
import pandas as pd
import re

In [2]:
high=pd.read_csv("C:\\Users\\owner\\Desktop\\데이터 분석 중간 프로젝트\\인프라\\서울시 고등학교 기본정보.csv",encoding="EUC-KR")

In [3]:
high.head()

,학교종류명,설립구분,표준학교코드,학교명,영문학교명,관할조직명,도로명우편번호,도로명주소,도로명상세주소,전화번호,...,고등학교일반실업구분명,특수목적고등학교계열명,입시전후기구분명,주야구분명,설립일자,개교기념일,시도교육청코드,시도교육청명,소재지명,적재일시
0,고등학교,공립,7011540,솔샘고등학교,Solsaem High School,서울특별시교육청,1190,서울특별시 강북구 인수봉로 39,/ 솔샘고등학교,02-982-6104,...,일반계,NaN,후기,주간,20090301,20090610,B10,서울특별시교육청,서울특별시,20230326
1,고등학교,사립,7011539,서울동구고등학교,SEOUL DONGGOO HIGH SCHOOL,서울특별시교육청,2834,서울특별시 성북구 성북로8길 71,/ 동구마케팅고등학교 (성북동),02-762-1301,...,전문계,NaN,전기,주간,19420617,19420617,B10,서울특별시교육청,서울특별시,20230326
2,고등학교,사립,7011513,서울정화고등학교,Seoul Jeonghwa High School,서울특별시교육청,2480,서울특별시 동대문구 홍릉로15길 50,(제기동)정화여자상업고등학교,02-960-1495,...,전문계,NaN,전기,주간,19080901,19080901,B10,서울특별시교육청,서울특별시,20230326
3,고등학교,사립,7011508,선일빅데이터고등학교,SUNIL BIGDATA HIGHSCHOOL,서울특별시교육청,3322,서울특별시 은평구 갈현로29길 27,/ 선일빅데이터고등학교 (갈현동),02-355-5648,...,전문계,NaN,전기,주간,19850108,19850311,B10,서울특별시교육청,서울특별시,20230326
4,고등학교,사립,7011507,대경생활과학고등학교,Daekyeong Life Science High School,서울특별시교육청,4592,서울특별시 중구 매봉18길 111,(신당동),02-2235-5155,...,전문계,NaN,전기,주간,19560228,19560416,B10,서울특별시교육청,서울특별시,20230326

In [4]:
high1=high["도로명주소"]

In [5]:
print(high1)

0         서울특별시 강북구 인수봉로 39
1        서울특별시 성북구 성북로8길 71
2      서울특별시 동대문구 홍릉로15길 50
3       서울특별시 은평구 갈현로29길 27
4        서울특별시 중구 매봉18길 111
               ...
316      서울특별시 강남구 영동대로 643
317       서울특별시 강남구 개포로 402
318        서울특별시 송파구 송이로 42
319    서울특별시 금천구 시흥대로38길 62
320     서울특별시 강남구 개포로22길 65
Name: 도로명주소, Length: 321, dtype: object

In [6]:
# 주소에서 구만 추출
list=[]
for i in range(321):
    address = high1[i]
    pattern_gu = re.compile(r"(\S+?[구군])")

    result = re.search(pattern_gu, address)
    print(result.group())
    list.append(result.group())

강북구
성북구
동대문구
은평구
중구
금천구
노원구
송파구
송파구
용산구
노원구
노원구
강서구
종로구
은평구
강남구
관악구
성북구
중구
관악구
강남구
성동구
성동구
은평구
은평구
성북구
강서구
강동구
양천구
구로구
성북구
강동구
서대문구
동대문구
송파구
관악구
성북구
강서구
노원구
마포구
중랑구
도봉구
강북구
강동구
은평구
강서구
양천구
은평구
노원구
송파구
강동구
은평구
강남구
강동구
마포구
노원구
중구
구로구
중구
도봉구
성동구
강서구
구로구
은평구
은평구
강북구
성동구
강서구
종로구
영등포구
구로구
동대문구
종로구
구로구
송파구
동대문구
은평구
서초구
성동구
마포구
중랑구
성북구
양천구
성동구
도봉구
양천구
강서구
중랑구
광진구
양천구
마포구
강남구
관악구
강남구
중구
노원구
노원구
영등포구
구로구
송파구
도봉구
중랑구
송파구
강서구
도봉구
성동구
관악구
노원구
노원구
노원구
송파구
도봉구
용산구
관악구
노원구
구로구
도봉구
금천구
노원구
노원구
서대문구
구로구
은평구
용산구
중구
송파구
구로구
강서구
강남구
관악구
구로구
동대문구
성동구
동작구
종로구
노원구
강서구
강남구
동대문구
중구
강서구
마포구
성북구
중랑구
노원구
강남구
강동구
강동구
성북구
서대문구
강서구
노원구
강서구
양천구
은평구
노원구
강북구
강남구
양천구
서대문구
강남구
종로구
강남구
강남구
도봉구
송파구
노원구
영등포구
중구
송파구
서대문구
중구
중구
강남구
구로구
노원구
성북구
용산구
은평구
강북구
송파구
강서구
노원구
관악구
강남구
양천구
양천구
강북구
용산구
동작구
은평구
마포구
강남구
중랑구
중랑구
서초구
서초구
용산구
성북구
관악구
동작구
광진구
은평구
은평구
도봉구
도봉구
종로구
강남구
관악구
서초구
노원구
강동구
서초구
종로구
용산구
송파구
양천구
종로구
강동구
용산구
송파구
관악구
금천구
서대문구
강서구
강서구
강서구
강서구
금천구
종로구
강동구
은평구
서초구
동대문구
강서구
강서구
종로구
노원구
노원구
성북구
강서구
광진구
광진구
광진구
종로구
은평구
동대문구
강남구
관악구
양천구
양천구
관악구
마포구
강동구
동대문구
동대문구
종로구
마포구
강서구
동작구
광진구
양천구
강동구
강북구
서대문구
중랑구
동대문구
강남구
송파구
중랑구
용산구
송파구
송파구
광진구
관악구
용산구
송파구
영등포구
영등포구
동작구
영등포구
영등포구
서초구
서초구
양천구
관악구
동작구
중구
성북구
서초구
송파구
마포구
종로구
서초구
노원구
관악구
서초구
성동구
강동구
중랑구
강동구
동작구
영등포구
관악구
금천구
양천구
구로구
구로구
광진구
광진구
영등포구
강서구
구로구
종로구
성북구
강남구
강남구
강남구
송파구
금천구
강남구

In [8]:
high["자치구별"]=list # 자치구별 컬럼 추가

In [10]:
high.head()

,학교종류명,설립구분,표준학교코드,학교명,영문학교명,관할조직명,도로명우편번호,도로명주소,도로명상세주소,전화번호,...,특수목적고등학교계열명,입시전후기구분명,주야구분명,설립일자,개교기념일,시도교육청코드,시도교육청명,소재지명,적재일시,자치구별
0,고등학교,공립,7011540,솔샘고등학교,Solsaem High School,서울특별시교육청,1190,서울특별시 강북구 인수봉로 39,/ 솔샘고등학교,02-982-6104,...,NaN,후기,주간,20090301,20090610,B10,서울특별시교육청,서울특별시,20230326,강북구
1,고등학교,사립,7011539,서울동구고등학교,SEOUL DONGGOO HIGH SCHOOL,서울특별시교육청,2834,서울특별시 성북구 성북로8길 71,/ 동구마케팅고등학교 (성북동),02-762-1301,...,NaN,전기,주간,19420617,19420617,B10,서울특별시교육청,서울특별시,20230326,성북구
2,고등학교,사립,7011513,서울정화고등학교,Seoul Jeonghwa High School,서울특별시교육청,2480,서울특별시 동대문구 홍릉로15길 50,(제기동)정화여자상업고등학교,02-960-1495,...,NaN,전기,주간,19080901,19080901,B10,서울특별시교육청,서울특별시,20230326,동대문구
3,고등학교,사립,7011508,선일빅데이터고등학교,SUNIL BIGDATA HIGHSCHOOL,서울특별시교육청,3322,서울특별시 은평구 갈현로29길 27,/ 선일빅데이터고등학교 (갈현동),02-355-5648,...,NaN,전기,주간,19850108,19850311,B10,서울특별시교육청,서울특별시,20230326,은평구
4,고등학교,사립,7011507,대경생활과학고등학교,Daekyeong Life Science High School,서울특별시교육청,4592,서울특별시 중구 매봉18길 111,(신당동),02-2235-5155,...,NaN,전기,주간,19560228,19560416,B10,서울특별시교육청,서울특별시,20230326,중구

In [15]:
high2=high[["학교명","자치구별"]]

In [16]:
high2

            학교명  자치구별
0        솔샘고등학교   강북구
1      서울동구고등학교   성북구
2      서울정화고등학교  동대문구
3    선일빅데이터고등학교   은평구
4    대경생활과학고등학교    중구
..          ...   ...
316      경기고등학교   강남구
317      개포고등학교   강남구
318      가락고등학교   송파구
319  국립전통예술고등학교   금천구
320    국립국악고등학교   강남구

[321 rows x 2 columns]

In [17]:
high_school=high2.groupby("자치구별").count() #자치구별 고등학교 갯수

In [18]:
high_school

      학교명
자치구별
강남구    22
강동구    14
강북구     7
강서구    23
관악구    17
광진구     9
구로구    14
금천구     6
노원구    25
도봉구    10
동대문구   11
동작구     7
마포구     9
서대문구    7
서초구    11
성동구     9
성북구    13
송파구    20
양천구    15
영등포구    9
용산구    10
은평구    18
종로구    14
중구     11
중랑구    10

In [19]:
high_school.columns=["고등학교수"]

In [25]:
high_school["고등학교수"]=high_school["고등학교수"].astype(int) # 데이터 정수형으로 변경

In [24]:
high_school.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 강남구 to 중랑구
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고등학교수   25 non-null     int32
dtypes: int32(1)
memory usage: 300.0+ bytes

In [22]:
high_school.to_csv("C:\\Users\\owner\\team project\\전처리 완\\high_school.csv")