#### 기준년도 : 2021년

In [ ]:
import pandas as pd

In [9]:
aca=pd.read_csv("C:\\Users\\owner\\Desktop\\데이터 분석 중간 프로젝트\\인프라\\사설학원+및+독서실(2009년+이후)_20230412182920.csv",header=4)

In [10]:
aca

,자치구별(1),자치구별(2),소계,소계.1,입시검정 및 보습,국제화,예능,특수교육,종합,기타,소계.2,직업기술,국제화.1,인문사회,기예,종합.1,소계.3,소계.4,소계.5,소계.6
0,합계,소계,13809,11647,7771,753,2277,1,322,523,2162,905,203,278,647,129,4610118,90833,49810,85564
1,합계,종로구,217,91,63,6,13,0,3,6,126,35,26,20,29,16,35746,2502,1341,1504
2,합계,중구,91,47,26,9,8,0,1,3,44,20,9,2,10,3,11678,1138,505,692
3,합계,용산구,137,116,63,21,26,0,4,2,21,10,2,2,5,2,14857,773,569,918
4,합계,성동구,290,247,153,14,55,0,16,9,43,22,1,3,15,2,60626,1422,939,1811
5,합계,광진구,426,364,247,23,68,0,7,19,62,24,5,3,27,3,87486,1885,1234,2538
6,합계,동대문구,359,308,203,16,78,0,4,7,51,30,3,0,14,4,30861,1705,1088,2273
7,합계,중랑구,257,232,159,6,48,0,10,9,25,12,0,0,12,1,22352,1136,747,1654
8,합계,성북구,451,430,296,19,101,0,4,10,21,9,1,0,11,0,33645,2171,1374,2942
9,합계,강북구,210,187,139,3,38,0,4,3,23,10,0,1,11,1,14294,721,490,1337
10,합계,도봉구,285,268,197,12,51,0,2,6,17,13,0,0,2,2,25797,1053,723,1836
11,합계,노원구,684,636,445,30,128,0,11,22,48,25,2,10,9,2,69114,4072,2136,4751
12,합계,은평구,509,472,346,17,91,0,5,13,37,19,0,1,12,5,214536,1898,1206,2928
13,합계,서대문구,342,287,202,17,53,0,5,10,55,19,7,13,10,6,601611,2437,1535,2109
14,합계,마포구,692,499,270,36,160,0,8,25,193,67,15,12,89,10,485239,4436,2514,4136
15,합계,양천구,979,947,681,54,145,0,31,36,32,16,4,1,11,0,157096,6919,3729,8224
16,합계,강서구,697,649,441,27,153,0,9,19,48,27,3,0,16,2,761995,2806,1954,4046
17,합계,구로구,386,345,225,17,86,0,6,11,41,25,3,1,6,6,73154,1669,1134,2494
18,합계,금천구,208,175,117,8,45,0,3,2,33,21,4,2,4,2,60226,973,602,1253
19,합계,영등포구,440,315,197,24,72,1,6,15,125,72,6,10,26,11,166734,2204,1439,2434
20,합계,동작구,487,345,223,21,70,0,12,19,142,22,1,88,21,10,69265,4315,1736,2801
21,합계,관악구,434,336,214,13,89,0,8,12,98,39,3,25,28,3,42416,2331,1354,2638
22,합계,서초구,1146,876,578,78,116,0,31,73,270,118,38,33,69,12,404623,9469,5482,6262
23,합계,강남구,2383,1898,1266,186,235,0,93,118,485,193,63,46,162,21,1050360,24559,10770,13038
24,합계,송파구,1045,963,603,68,214,0,26,52,82,38,5,4,32,3,73254,5460,3474,6729
25,합계,강동구,654,614,417,28,134,0,13,22,40,19,2,1,16,2,43153,2779,1735,4216

In [22]:
aca1=aca[["자치구별(2)","소계.1","소계.2"]]

In [23]:
aca1.columns=["자치구별","학교교과학원수","평생교육학원수"]

In [24]:
aca1.drop(0,inplace=True)

C:\Users\owner\AppData\Local\Temp\ipykernel_5980\3874090698.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aca1.drop(0,inplace=True)

In [25]:
aca1

    자치구별  학교교과학원수  평생교육학원수
1    종로구       91      126
2     중구       47       44
3    용산구      116       21
4    성동구      247       43
5    광진구      364       62
6   동대문구      308       51
7    중랑구      232       25
8    성북구      430       21
9    강북구      187       23
10   도봉구      268       17
11   노원구      636       48
12   은평구      472       37
13  서대문구      287       55
14   마포구      499      193
15   양천구      947       32
16   강서구      649       48
17   구로구      345       41
18   금천구      175       33
19  영등포구      315      125
20   동작구      345      142
21   관악구      336       98
22   서초구      876      270
23   강남구     1898      485
24   송파구      963       82
25   강동구      614       40

In [29]:
aca1.set_index(["자치구별"],inplace=True)

In [30]:
aca1["학원총합계"]=aca1["학교교과학원수"]+aca1["평생교육학원수"]

C:\Users\owner\AppData\Local\Temp\ipykernel_5980\2961539044.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aca1["학원총합계"]=aca1["학교교과학원수"]+aca1["평생교육학원수"]

In [32]:
academy=aca1

In [34]:
academy.to_csv("C:\\Users\\owner\\team project\\전처리 완\\academy.csv")