In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:\\Windows\\Fonts\\malgun.ttf").get_name()
plt.rc("font", family=font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"] = False

import xml.etree.ElementTree as et

import urllib.request as req
import requests
import json

import urllib.request as req
from urllib.error import HTTPError, URLError 

from bs4 import BeautifulSoup

from urllib.request import urlopen

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import os
import re

from scipy.stats import shapiro
from scipy import stats
import scipy

# 버스정류장

In [2]:
bus = pd.read_csv('final_bus_gu_year.csv', index_col=0)
bus

    자치구별  2018  2019  2020  2021  2022
0    강남구   534   548   545   520   823
1    강동구   349   385   383   365   573
2    강북구   460   448   415   409   454
3    강서구   576   603   611   569   801
4    관악구   485   485   470   467   638
5    광진구   286   292   288   270   380
6    구로구   478   513   510   497   720
7    금천구   342   362   357   342   540
8    노원구   537   544   538   527   736
9    도봉구   386   391   366   358   448
10  동대문구   318   319   311   303   408
11   동작구   460   447   440   437   545
12   마포구   569   568   570   563   764
13  서대문구   444   446   457   454   542
14   서초구   648   649   638   605   962
15   성동구   439   442   433   445   502
16   성북구   611   604   599   601   670
17   송파구   413   429   440   414   716
18   양천구   363   365   320   317   491
19  영등포구   491   504   494   466   679
20   용산구   349   344   327   328   441
21   은평구   499   511   501   497   725
22   종로구   382   375   374   369   472
23    중구   207   211   241   200   309
24   중랑구   379   380   382   380   479

## 전월세가

In [3]:
buy2018 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2018_data.csv')
buy2018.drop(index=25, inplace=True)
buy2018.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2018가격'}, inplace=True)
buy2018 = buy2018[['자치구별', '2018가격']]
buy2018

    자치구별  2018가격
0    강남구   654.0
1    강동구   472.0
2    강북구   336.0
3    강서구   406.0
4    관악구   369.0
5    광진구   538.0
6    구로구   360.0
7    금천구   335.0
8    노원구   297.0
9    도봉구   276.0
10  동대문구   408.0
11   동작구   502.0
12   마포구   512.0
13  서대문구   436.0
14   서초구   645.0
15   성동구   542.0
16   성북구   407.0
17   송파구   577.0
18   양천구   494.0
19  영등포구   445.0
20   용산구   508.0
21   은평구   369.0
22   종로구   419.0
23    중구   482.0
24   중랑구   305.0

In [4]:
buy2019 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2019_data.csv')
buy2019.drop(index=25, inplace=True)
buy2019.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2019가격'}, inplace=True)
buy2019 = buy2019[['자치구별', '2019가격']]
buy2019

    자치구별  2019가격
0    강남구   676.0
1    강동구   471.0
2    강북구   339.0
3    강서구   442.0
4    관악구   380.0
5    광진구   546.0
6    구로구   362.0
7    금천구   346.0
8    노원구   304.0
9    도봉구   282.0
10  동대문구   423.0
11   동작구   499.0
12   마포구   536.0
13  서대문구   463.0
14   서초구   638.0
15   성동구   558.0
16   성북구   415.0
17   송파구   576.0
18   양천구   483.0
19  영등포구   478.0
20   용산구   532.0
21   은평구   395.0
22   종로구   538.0
23    중구   453.0
24   중랑구   370.0

In [5]:
buy2020 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2020_data.csv')
buy2020.drop(index=25, inplace=True)
buy2020.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2020가격'}, inplace=True)
buy2020 = buy2020[['자치구별', '2020가격']]
buy2020

    자치구별  2020가격
0    강남구   781.0
1    강동구   515.0
2    강북구   394.0
3    강서구   453.0
4    관악구   411.0
5    광진구   604.0
6    구로구   375.0
7    금천구   412.0
8    노원구   332.0
9    도봉구   314.0
10  동대문구   474.0
11   동작구   569.0
12   마포구   519.0
13  서대문구   499.0
14   서초구   760.0
15   성동구   618.0
16   성북구   462.0
17   송파구   647.0
18   양천구   527.0
19  영등포구   506.0
20   용산구   579.0
21   은평구   439.0
22   종로구   479.0
23    중구   549.0
24   중랑구   391.0

In [6]:
buy2021 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2021_data.csv')
buy2021.drop(index=25, inplace=True)
buy2021.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2021가격'}, inplace=True)
buy2021 = buy2021[['자치구별', '2021가격']]
buy2021

    자치구별  2021가격
0    강남구   824.0
1    강동구   516.0
2    강북구   393.0
3    강서구   470.0
4    관악구   460.0
5    광진구   667.0
6    구로구   364.0
7    금천구   403.0
8    노원구   368.0
9    도봉구   355.0
10  동대문구   513.0
11   동작구   630.0
12   마포구   585.0
13  서대문구   533.0
14   서초구   796.0
15   성동구   658.0
16   성북구   497.0
17   송파구   672.0
18   양천구   535.0
19  영등포구   554.0
20   용산구   623.0
21   은평구   444.0
22   종로구   568.0
23    중구   566.0
24   중랑구   419.0

In [7]:
buy2022 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2022_data.csv')
buy2022.drop(index=25, inplace=True)
buy2022.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2022가격'}, inplace=True)
buy2022 = buy2022[['자치구별', '2022가격']]
buy2022

    자치구별  2022가격
0    강남구   785.0
1    강동구   540.0
2    강북구   376.0
3    강서구   464.0
4    관악구   442.0
5    광진구   642.0
6    구로구   370.0
7    금천구   439.0
8    노원구   347.0
9    도봉구   323.0
10  동대문구   504.0
11   동작구   587.0
12   마포구   563.0
13  서대문구   508.0
14   서초구   813.0
15   성동구   650.0
16   성북구   470.0
17   송파구   656.0
18   양천구   541.0
19  영등포구   551.0
20   용산구   564.0
21   은평구   458.0
22   종로구   520.0
23    중구   547.0
24   중랑구   380.0

## 버스정류장&전월세

In [8]:
from functools import reduce
import pandas as pd
dfs = [bus, buy2018, buy2019, buy2020, buy2021, buy2022]
df = reduce(lambda left, right: pd.merge(left, right, on='자치구별'), dfs)
df

    자치구별  2018  2019  2020  2021  2022  2018가격  2019가격  2020가격  2021가격  2022가격
0    강남구   534   548   545   520   823   654.0   676.0   781.0   824.0   785.0
1    강동구   349   385   383   365   573   472.0   471.0   515.0   516.0   540.0
2    강북구   460   448   415   409   454   336.0   339.0   394.0   393.0   376.0
3    강서구   576   603   611   569   801   406.0   442.0   453.0   470.0   464.0
4    관악구   485   485   470   467   638   369.0   380.0   411.0   460.0   442.0
5    광진구   286   292   288   270   380   538.0   546.0   604.0   667.0   642.0
6    구로구   478   513   510   497   720   360.0   362.0   375.0   364.0   370.0
7    금천구   342   362   357   342   540   335.0   346.0   412.0   403.0   439.0
8    노원구   537   544   538   527   736   297.0   304.0   332.0   368.0   347.0
9    도봉구   386   391   366   358   448   276.0   282.0   314.0   355.0   323.0
10  동대문구   318   319   311   303   408   408.0   423.0   474.0   513.0   504.0
11   동작구   460   447   440   437   545   502.0   499.0   569.0   630.0   587.0
12   마포구   569   568   570   563   764   512.0   536.0   519.0   585.0   563.0
13  서대문구   444   446   457   454   542   436.0   463.0   499.0   533.0   508.0
14   서초구   648   649   638   605   962   645.0   638.0   760.0   796.0   813.0
15   성동구   439   442   433   445   502   542.0   558.0   618.0   658.0   650.0
16   성북구   611   604   599   601   670   407.0   415.0   462.0   497.0   470.0
17   송파구   413   429   440   414   716   577.0   576.0   647.0   672.0   656.0
18   양천구   363   365   320   317   491   494.0   483.0   527.0   535.0   541.0
19  영등포구   491   504   494   466   679   445.0   478.0   506.0   554.0   551.0
20   용산구   349   344   327   328   441   508.0   532.0   579.0   623.0   564.0
21   은평구   499   511   501   497   725   369.0   395.0   439.0   444.0   458.0
22   종로구   382   375   374   369   472   419.0   538.0   479.0   568.0   520.0
23    중구   207   211   241   200   309   482.0   453.0   549.0   566.0   547.0
24   중랑구   379   380   382   380   479   305.0   370.0   391.0   419.0   380.0

In [9]:
df.to_csv('bus_rentprice_18-22.csv')

### 정규성

In [10]:
shapiro_test = stats.shapiro(df['2018'])
shapiro_test # 정규분포 맞음

ShapiroResult(statistic=0.9897786378860474, pvalue=0.994960606098175)

In [11]:
shapiro_test = stats.shapiro(df['2019'])
shapiro_test # 정규분포 맞음

ShapiroResult(statistic=0.9852784872055054, pvalue=0.9661734104156494)

In [12]:
shapiro_test = stats.shapiro(df['2020'])
shapiro_test # 정규분포 맞음

ShapiroResult(statistic=0.9804011583328247, pvalue=0.8929436206817627)

In [13]:
shapiro_test = stats.shapiro(df['2021'])
shapiro_test # 정규분포 맞음

ShapiroResult(statistic=0.9821061491966248, pvalue=0.9234092235565186)

In [14]:
shapiro_test = stats.shapiro(df['2022'])
shapiro_test # 정규분포 맞음

ShapiroResult(statistic=0.96748948097229, pvalue=0.5822901725769043)

### 상관분석

In [15]:
print(scipy.stats.pearsonr(df['2018'], df['2018가격'])) # p-value 어떻게 보는 것?
print(scipy.stats.pearsonr(df['2019'], df['2019가격']))
print(scipy.stats.pearsonr(df['2020'], df['2020가격']))
print(scipy.stats.pearsonr(df['2021'], df['2021가격']))
print(scipy.stats.pearsonr(df['2022'], df['2022가격']))

PearsonRResult(statistic=0.10451252523852281, pvalue=0.6190659331652723)
PearsonRResult(statistic=0.11492339457664502, pvalue=0.5843673122104055)
PearsonRResult(statistic=0.11051202665363669, pvalue=0.598967015658357)
PearsonRResult(statistic=0.07906437145318054, pvalue=0.7071608776794067)
PearsonRResult(statistic=0.28943985314804727, pvalue=0.1605100586538573)

In [16]:
corr = df.corr(method='pearson')
corr

,2018,2019,2020,2021,2022,2018가격,2019가격,2020가격,2021가격,2022가격
2018,1.000000,0.992746,0.978769,0.986035,0.872916,0.104513,0.124523,0.094713,0.104957,0.120596
2019,0.992746,1.000000,0.990633,0.990596,0.908789,0.099871,0.114923,0.086577,0.084239,0.112949
2020,0.978769,0.990633,1.000000,0.991855,0.919216,0.122459,0.141761,0.110512,0.109010,0.135984
2021,0.986035,0.990596,0.991855,1.000000,0.887669,0.086753,0.113737,0.073342,0.079064,0.098995
2022,0.872916,0.908789,0.919216,0.887669,1.000000,0.271661,0.270506,0.260625,0.230259,0.289440
2018가격,0.104513,0.099871,0.122459,0.086753,0.271661,1.000000,0.961907,0.980591,0.967598,0.976062
2019가격,0.124523,0.114923,0.141761,0.113737,0.270506,0.961907,1.000000,0.954467,0.970133,0.958809
2020가격,0.094713,0.086577,0.110512,0.073342,0.260625,0.980591,0.954467,1.000000,0.982246,0.988748
2021가격,0.104957,0.084239,0.109010,0.079064,0.230259,0.967598,0.970133,0.982246,1.000000,0.983148
2022가격,0.120596,0.112949,0.135984,0.098995,0.289440,0.976062,0.958809,0.988748,0.983148,1.000000

### 회귀분석

In [17]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(df['2018'].values.reshape(-1, 1), df['2018가격'].values.reshape(-1, 1))
lr.coef_[0]

array([0.10085084])

In [18]:
import statsmodels.api as sm
results = sm.OLS(df['2018가격'], sm.add_constant(df['2018'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2018가격   R-squared:                       0.011
Model:                            OLS   Adj. R-squared:                 -0.032
Method:                 Least Squares   F-statistic:                    0.2540
Date:                Mon, 24 Apr 2023   Prob (F-statistic):              0.619
Time:                        01:59:32   Log-Likelihood:                -150.63
No. Observations:                  25   AIC:                             305.3
Df Residuals:                      23   BIC:                             307.7
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        399.3655     90.526      4.412      0.000     212.098     586.633
2018           0.1009      0.200      0.504      0.619      -0.313       0.515
==============================================================================
Omnibus:                        1.270   Durbin-Watson:                   1.396
Prob(Omnibus):                  0.530   Jarque-Bera (JB):                0.975
Skew:                           0.209   Prob(JB):                        0.614
Kurtosis:                       2.127   Cond. No.                     1.96e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.96e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

- F-statistic의 p-value 값은 Prob(F-statistic)으로 표현되는데, 이는 0.05보다 작기에 이 회귀식은 회귀분석 모델 전체에 대해 통계적으로 의미가 있다고 볼 수 있습니다.

- 중간쯤에 보면 coef와 변수 x1의 p-value 값이 나와있습니다. 여기서 x1은 bmi이고 이 변수의 p-value가 0.000으로 표기 되어 있기에 0.05보다 작으므로 target을 설명하는데 유의하다고 판단할 수 있습니다.

In [19]:
results = sm.OLS(df['2019가격'], sm.add_constant(df['2019'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2019가격   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                 -0.030
Method:                 Least Squares   F-statistic:                    0.3078
Date:                Mon, 24 Apr 2023   Prob (F-statistic):              0.584
Time:                        01:59:35   Log-Likelihood:                -150.14
No. Observations:                  25   AIC:                             304.3
Df Residuals:                      23   BIC:                             306.7
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        411.8317     89.547      4.599      0.000     226.589     597.075
2019           0.1083      0.195      0.555      0.584      -0.296       0.512
==============================================================================
Omnibus:                        0.698   Durbin-Watson:                   1.403
Prob(Omnibus):                  0.705   Jarque-Bera (JB):                0.682
Skew:                           0.080   Prob(JB):                        0.711
Kurtosis:                       2.207   Cond. No.                     2.01e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.01e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [20]:
results = sm.OLS(df['2020가격'], sm.add_constant(df['2020'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2020가격   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                 -0.031
Method:                 Least Squares   F-statistic:                    0.2844
Date:                Mon, 24 Apr 2023   Prob (F-statistic):              0.599
Time:                        01:59:36   Log-Likelihood:                -154.03
No. Observations:                  25   AIC:                             312.1
Df Residuals:                      23   BIC:                             314.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        450.7621    103.315      4.363      0.000     237.039     664.486
2020           0.1217      0.228      0.533      0.599      -0.350       0.594
==============================================================================
Omnibus:                        1.371   Durbin-Watson:                   1.442
Prob(Omnibus):                  0.504   Jarque-Bera (JB):                1.095
Skew:                           0.490   Prob(JB):                        0.579
Kurtosis:                       2.698   Cond. No.                     1.96e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.96e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [21]:
results = sm.OLS(df['2021가격'], sm.add_constant(df['2021'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2021가격   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                 -0.037
Method:                 Least Squares   F-statistic:                    0.1447
Date:                Mon, 24 Apr 2023   Prob (F-statistic):              0.707
Time:                        01:59:37   Log-Likelihood:                -155.94
No. Observations:                  25   AIC:                             315.9
Df Residuals:                      23   BIC:                             318.3
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        495.9689    109.690      4.522      0.000     269.057     722.881
2021           0.0947      0.249      0.380      0.707      -0.420       0.610
==============================================================================
Omnibus:                        1.074   Durbin-Watson:                   1.467
Prob(Omnibus):                  0.584   Jarque-Bera (JB):                1.013
Skew:                           0.423   Prob(JB):                        0.602
Kurtosis:                       2.494   Cond. No.                     1.87e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.87e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [22]:
results = sm.OLS(df['2022가격'], sm.add_constant(df['2022'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2022가격   R-squared:                       0.084
Model:                            OLS   Adj. R-squared:                  0.044
Method:                 Least Squares   F-statistic:                     2.103
Date:                Mon, 24 Apr 2023   Prob (F-statistic):              0.161
Time:                        01:59:38   Log-Likelihood:                -154.45
No. Observations:                  25   AIC:                             312.9
Df Residuals:                      23   BIC:                             315.3
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        389.3021     94.415      4.123      0.000     193.990     584.614
2022           0.2232      0.154      1.450      0.161      -0.095       0.542
==============================================================================
Omnibus:                        1.154   Durbin-Watson:                   1.598
Prob(Omnibus):                  0.562   Jarque-Bera (JB):                0.863
Skew:                           0.099   Prob(JB):                        0.650
Kurtosis:                       2.112   Cond. No.                     2.38e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.38e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

---
---
---

### 4년 합친 것

In [23]:
bus_long = pd.melt(bus, id_vars=['자치구별'], var_name='year', value_name='bus_num')
bus_long

    자치구별  year  bus_num
0    강남구  2018      534
1    강동구  2018      349
2    강북구  2018      460
3    강서구  2018      576
4    관악구  2018      485
..   ...   ...      ...
120  용산구  2022      441
121  은평구  2022      725
122  종로구  2022      472
123   중구  2022      309
124  중랑구  2022      479

[125 rows x 3 columns]

In [24]:
lst1=[i for i in df['2018가격']]
lst2=[i for i in df['2019가격']]
lst3=[i for i in df['2020가격']]
lst4=[i for i in df['2021가격']]
lst5=[i for i in df['2022가격']]

In [25]:
lst= lst1 + lst2 + lst3 + lst4 + lst5

In [28]:
lst

[1702.0,
 858.0,
 563.0,
 728.0,
 642.0,
 943.0,
 595.0,
 516.0,
 601.0,
 504.0,
 693.0,
 880.0,
 989.0,
 727.0,
 1461.0,
 1048.0,
 629.0,
 1201.0,
 811.0,
 845.0,
 1200.0,
 627.0,
 764.0,
 871.0,
 541.0,
 2051.0,
 1007.0,
 665.0,
 852.0,
 757.0,
 1105.0,
 707.0,
 619.0,
 703.0,
 594.0,
 840.0,
 1066.0,
 1221.0,
 922.0,
 1755.0,
 1245.0,
 771.0,
 1440.0,
 1038.0,
 1039.0,
 1463.0,
 729.0,
 1015.0,
 1024.0,
 660.0,
 2117.0,
 1170.0,
 771.0,
 964.0,
 871.0,
 1291.0,
 769.0,
 739.0,
 844.0,
 675.0,
 995.0,
 1230.0,
 1344.0,
 1038.0,
 1913.0,
 1471.0,
 914.0,
 1601.0,
 1143.0,
 1180.0,
 1594.0,
 827.0,
 1034.0,
 1138.0,
 760.0,
 2351.0,
 1437.0,
 939.0,
 1175.0,
 1089.0,
 1517.0,
 945.0,
 914.0,
 1116.0,
 899.0,
 1174.0,
 1670.0,
 1568.0,
 1256.0,
 2208.0,
 1806.0,
 1144.0,
 1983.0,
 1353.0,
 1378.0,
 1903.0,
 1042.0,
 1239.0,
 1285.0,
 969.0,
 2296.0,
 1322.0,
 942.0,
 1036.0,
 1045.0,
 1424.0,
 881.0,
 1014.0,
 1116.0,
 890.0,
 1108.0,
 1422.0,
 1567.0,
 1219.0,
 2328.0,
 1841.0,
 1129.0,
 1965.0,
 1310.0,
 1220.0,
 1986.0,
 1056.0,
 1175.0,
 1217.0,
 994.0]

In [26]:
bus_long['price'] = lst

In [27]:
bus_long

    자치구별  year  bus_num  price
0    강남구  2018      534  654.0
1    강동구  2018      349  472.0
2    강북구  2018      460  336.0
3    강서구  2018      576  406.0
4    관악구  2018      485  369.0
..   ...   ...      ...    ...
120  용산구  2022      441  564.0
121  은평구  2022      725  458.0
122  종로구  2022      472  520.0
123   중구  2022      309  547.0
124  중랑구  2022      479  380.0

[125 rows x 4 columns]

### 정규성

In [28]:
shapiro_test = stats.shapiro(bus_long['bus_num'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.9708263278007507, pvalue=0.008304862305521965)

### 상관분석

In [29]:
print(scipy.stats.spearmanr(bus_long['bus_num'], bus_long['price']))

SpearmanrResult(correlation=0.028214817889283633, pvalue=0.7547788544417923)

### 회귀분석

In [30]:
results = sm.OLS(bus_long['price'], sm.add_constant(bus_long['bus_num'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.031
Model:                            OLS   Adj. R-squared:                  0.023
Method:                 Least Squares   F-statistic:                     3.949
Date:                Mon, 24 Apr 2023   Prob (F-statistic):             0.0491
Time:                        02:00:05   Log-Likelihood:                -771.91
No. Observations:                 125   AIC:                             1548.
Df Residuals:                     123   BIC:                             1553.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        419.3796     38.642     10.853      0.000     342.891     495.868
bus_num        0.1574      0.079      1.987      0.049       0.001       0.314
==============================================================================
Omnibus:                        3.621   Durbin-Watson:                   1.676
Prob(Omnibus):                  0.164   Jarque-Bera (JB):                3.619
Skew:                           0.380   Prob(JB):                        0.164
Kurtosis:                       2.659   Cond. No.                     1.80e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.8e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""