In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:\\Windows\\Fonts\\malgun.ttf").get_name()
plt.rc("font", family=font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"] = False

import xml.etree.ElementTree as et

import urllib.request as req
import requests
import json

import urllib.request as req
from urllib.error import HTTPError, URLError 

from bs4 import BeautifulSoup

from urllib.request import urlopen

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import os
import re

from scipy.stats import shapiro
from scipy import stats
import scipy

# 범죄

In [3]:
crime = pd.read_csv('C:/acorn/midproject/crimerate/final_crime_gu_year.csv', index_col=0)
crime

    자치구별  2018  2019  2020  2021
0    종로구   364   370   272   271
1     중구   357   314   283   282
2    용산구   417   362   319   248
3    성동구   204   205   171   220
4    광진구   363   415   352   325
5   동대문구   243   249   244   282
6    중랑구   238   212   276   273
7    성북구   303   259   212   222
8    강북구   273   239   217   222
9    도봉구   177   136   131   131
10   노원구   293   272   236   293
11   은평구   312   283   251   293
12  서대문구   278   268   251   292
13   마포구   735   673   577   524
14   양천구   193   199   189   202
15   강서구   424   442   410   434
16   구로구   405   363   344   341
17   금천구   273   221   183   246
18  영등포구   592   520   484   480
19   동작구   416   367   305   304
20   관악구   545   579   557   528
21   서초구   635   785   578   540
22   강남구  1010  1280  1048   946
23   송파구   515   459   444   496
24   강동구   241   280   289   234

## 매매가

In [22]:
buy2018 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_buysell_price_2018-22/save_point3_apt_buysell_2018_data.csv')
buy2018.drop(index=25, inplace=True)
buy2018.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2018가격'}, inplace=True)
buy2018 = buy2018[['자치구별', '2018가격']]
buy2018

    자치구별  2018가격
0    강남구  1702.0
1    강동구   858.0
2    강북구   563.0
3    강서구   728.0
4    관악구   642.0
5    광진구   943.0
6    구로구   595.0
7    금천구   516.0
8    노원구   601.0
9    도봉구   504.0
10  동대문구   693.0
11   동작구   880.0
12   마포구   989.0
13  서대문구   727.0
14   서초구  1461.0
15   성동구  1048.0
16   성북구   629.0
17   송파구  1201.0
18   양천구   811.0
19  영등포구   845.0
20   용산구  1200.0
21   은평구   627.0
22   종로구   764.0
23    중구   871.0
24   중랑구   541.0

In [23]:
buy2019 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_buysell_price_2018-22/save_point3_apt_buysell_2019_data.csv')
buy2019.drop(index=25, inplace=True)
buy2019.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2019가격'}, inplace=True)
buy2019 = buy2019[['자치구별', '2019가격']]
buy2019

    자치구별  2019가격
0    강남구  2051.0
1    강동구  1007.0
2    강북구   665.0
3    강서구   852.0
4    관악구   757.0
5    광진구  1105.0
6    구로구   707.0
7    금천구   619.0
8    노원구   703.0
9    도봉구   594.0
10  동대문구   840.0
11   동작구  1066.0
12   마포구  1221.0
13  서대문구   922.0
14   서초구  1755.0
15   성동구  1245.0
16   성북구   771.0
17   송파구  1440.0
18   양천구  1038.0
19  영등포구  1039.0
20   용산구  1463.0
21   은평구   729.0
22   종로구  1015.0
23    중구  1024.0
24   중랑구   660.0

In [24]:
buy2020 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_buysell_price_2018-22/save_point3_apt_buysell_2020_data.csv')
buy2020.drop(index=25, inplace=True)
buy2020.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2020가격'}, inplace=True)
buy2020 = buy2020[['자치구별', '2020가격']]
buy2020

    자치구별  2020가격
0    강남구  2117.0
1    강동구  1170.0
2    강북구   771.0
3    강서구   964.0
4    관악구   871.0
5    광진구  1291.0
6    구로구   769.0
7    금천구   739.0
8    노원구   844.0
9    도봉구   675.0
10  동대문구   995.0
11   동작구  1230.0
12   마포구  1344.0
13  서대문구  1038.0
14   서초구  1913.0
15   성동구  1471.0
16   성북구   914.0
17   송파구  1601.0
18   양천구  1143.0
19  영등포구  1180.0
20   용산구  1594.0
21   은평구   827.0
22   종로구  1034.0
23    중구  1138.0
24   중랑구   760.0

In [26]:
buy2021 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_buysell_price_2018-22/save_point3_apt_buysell_2021_data.csv')
buy2021.drop(index=25, inplace=True)
buy2021.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2021가격'}, inplace=True)
buy2021 = buy2021[['자치구별', '2021가격']]
buy2021

    자치구별  2021가격
0    강남구  2351.0
1    강동구  1437.0
2    강북구   939.0
3    강서구  1175.0
4    관악구  1089.0
5    광진구  1517.0
6    구로구   945.0
7    금천구   914.0
8    노원구  1116.0
9    도봉구   899.0
10  동대문구  1174.0
11   동작구  1670.0
12   마포구  1568.0
13  서대문구  1256.0
14   서초구  2208.0
15   성동구  1806.0
16   성북구  1144.0
17   송파구  1983.0
18   양천구  1353.0
19  영등포구  1378.0
20   용산구  1903.0
21   은평구  1042.0
22   종로구  1239.0
23    중구  1285.0
24   중랑구   969.0

## 범죄&매매가

In [27]:
from functools import reduce
import pandas as pd
dfs = [crime, buy2018, buy2019, buy2020, buy2021]
df = reduce(lambda left, right: pd.merge(left, right, on='자치구별'), dfs)
df

    자치구별  2018  2019  2020  2021  2018가격  2019가격  2020가격  2021가격
0    종로구   364   370   272   271   764.0  1015.0  1034.0  1239.0
1     중구   357   314   283   282   871.0  1024.0  1138.0  1285.0
2    용산구   417   362   319   248  1200.0  1463.0  1594.0  1903.0
3    성동구   204   205   171   220  1048.0  1245.0  1471.0  1806.0
4    광진구   363   415   352   325   943.0  1105.0  1291.0  1517.0
5   동대문구   243   249   244   282   693.0   840.0   995.0  1174.0
6    중랑구   238   212   276   273   541.0   660.0   760.0   969.0
7    성북구   303   259   212   222   629.0   771.0   914.0  1144.0
8    강북구   273   239   217   222   563.0   665.0   771.0   939.0
9    도봉구   177   136   131   131   504.0   594.0   675.0   899.0
10   노원구   293   272   236   293   601.0   703.0   844.0  1116.0
11   은평구   312   283   251   293   627.0   729.0   827.0  1042.0
12  서대문구   278   268   251   292   727.0   922.0  1038.0  1256.0
13   마포구   735   673   577   524   989.0  1221.0  1344.0  1568.0
14   양천구   193   199   189   202   811.0  1038.0  1143.0  1353.0
15   강서구   424   442   410   434   728.0   852.0   964.0  1175.0
16   구로구   405   363   344   341   595.0   707.0   769.0   945.0
17   금천구   273   221   183   246   516.0   619.0   739.0   914.0
18  영등포구   592   520   484   480   845.0  1039.0  1180.0  1378.0
19   동작구   416   367   305   304   880.0  1066.0  1230.0  1670.0
20   관악구   545   579   557   528   642.0   757.0   871.0  1089.0
21   서초구   635   785   578   540  1461.0  1755.0  1913.0  2208.0
22   강남구  1010  1280  1048   946  1702.0  2051.0  2117.0  2351.0
23   송파구   515   459   444   496  1201.0  1440.0  1601.0  1983.0
24   강동구   241   280   289   234   858.0  1007.0  1170.0  1437.0

In [53]:
df.to_csv('crime_price_18-22.csv')

### 정규성

In [35]:
shapiro_test = stats.shapiro(df['2018'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.8547165989875793, pvalue=0.0021672924049198627)

In [36]:
shapiro_test = stats.shapiro(df['2019'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.7616845369338989, pvalue=5.567202242673375e-05)

In [37]:
shapiro_test = stats.shapiro(df['2020'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.7888317704200745, pvalue=0.00014889816520735621)

In [38]:
shapiro_test = stats.shapiro(df['2021'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.7921955585479736, pvalue=0.00016893752035684884)

### 상관분석

In [40]:
print(scipy.stats.spearmanr(df['2018'], df['2018가격'])) # p-value 어떻게 보는 것?
print(scipy.stats.spearmanr(df['2019'], df['2019가격']))
print(scipy.stats.spearmanr(df['2020'], df['2020가격']))
print(scipy.stats.spearmanr(df['2021'], df['2021가격']))

SpearmanrResult(correlation=0.5562608296781894, pvalue=0.003882482893581519)
SpearmanrResult(correlation=0.5861538461538462, pvalue=0.0020760584806934035)
SpearmanrResult(correlation=0.5589536552713755, pvalue=0.00367825454397862)
SpearmanrResult(correlation=0.39330389466146665, pvalue=0.05176895358116649)

In [34]:
corr = df.corr(method='spearman')
corr

,2018,2019,2020,2021,2018가격,2019가격,2020가격,2021가격
2018,1.000000,0.962877,0.894960,0.873942,0.556261,0.560877,0.523562,0.503558
2019,0.962877,1.000000,0.941335,0.900520,0.602308,0.586154,0.563846,0.546154
2020,0.894960,0.941335,1.000000,0.894342,0.593960,0.572802,0.558954,0.551260
2021,0.873942,0.900520,0.894342,1.000000,0.427939,0.411006,0.401770,0.393304
2018가격,0.556261,0.602308,0.593960,0.427939,1.000000,0.988462,0.988462,0.984615
2019가격,0.560877,0.586154,0.572802,0.411006,0.988462,1.000000,0.988462,0.980000
2020가격,0.523562,0.563846,0.558954,0.401770,0.988462,0.988462,1.000000,0.992308
2021가격,0.503558,0.546154,0.551260,0.393304,0.984615,0.980000,0.992308,1.000000

### 회귀분석

In [47]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(df['2018'].values.reshape(-1, 1), df['2018가격'].values.reshape(-1, 1))
lr.coef_[0]

array([1.11293487])

In [43]:
import statsmodels.api as sm
results = sm.OLS(df['2018가격'], sm.add_constant(df['2018'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2018가격   R-squared:                       0.517
Model:                            OLS   Adj. R-squared:                  0.496
Method:                 Least Squares   F-statistic:                     24.61
Date:                Sun, 23 Apr 2023   Prob (F-statistic):           5.14e-05
Time:                        21:27:24   Log-Likelihood:                -168.41
No. Observations:                  25   AIC:                             340.8
Df Residuals:                      23   BIC:                             343.3
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        401.0224     97.731      4.103      0.000     198.851     603.194
2018           1.1129      0.224      4.961      0.000       0.649       1.577
==============================================================================
Omnibus:                        1.445   Durbin-Watson:                   1.302
Prob(Omnibus):                  0.486   Jarque-Bera (JB):                1.242
Skew:                           0.385   Prob(JB):                        0.537
Kurtosis:                       2.226   Cond. No.                     1.00e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large,  1e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

- F-statistic의 p-value 값은 Prob(F-statistic)으로 표현되는데, 이는 0.05보다 작기에 이 회귀식은 회귀분석 모델 전체에 대해 통계적으로 의미가 있다고 볼 수 있습니다.

- 중간쯤에 보면 coef와 변수 x1의 p-value 값이 나와있습니다. 여기서 x1은 bmi이고 이 변수의 p-value가 0.000으로 표기 되어 있기에 0.05보다 작으므로 target을 설명하는데 유의하다고 판단할 수 있습니다.

In [54]:
results = sm.OLS(df['2019가격'], sm.add_constant(df['2019'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2019가격   R-squared:                       0.594
Model:                            OLS   Adj. R-squared:                  0.576
Method:                 Least Squares   F-statistic:                     33.65
Date:                Sun, 23 Apr 2023   Prob (F-statistic):           6.55e-06
Time:                        22:16:32   Log-Likelihood:                -171.04
No. Observations:                  25   AIC:                             346.1
Df Residuals:                      23   BIC:                             348.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        560.7833     90.925      6.168      0.000     372.690     748.877
2019           1.1555      0.199      5.801      0.000       0.743       1.568
==============================================================================
Omnibus:                        1.055   Durbin-Watson:                   1.517
Prob(Omnibus):                  0.590   Jarque-Bera (JB):                0.760
Skew:                           0.414   Prob(JB):                        0.684
Kurtosis:                       2.792   Cond. No.                         879.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [55]:
results = sm.OLS(df['2020가격'], sm.add_constant(df['2020'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2020가격   R-squared:                       0.468
Model:                            OLS   Adj. R-squared:                  0.445
Method:                 Least Squares   F-statistic:                     20.23
Date:                Sun, 23 Apr 2023   Prob (F-statistic):           0.000163
Time:                        22:16:51   Log-Likelihood:                -175.09
No. Observations:                  25   AIC:                             354.2
Df Residuals:                      23   BIC:                             356.6
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        681.8078    115.194      5.919      0.000     443.511     920.105
2020           1.3160      0.293      4.498      0.000       0.711       1.921
==============================================================================
Omnibus:                        0.848   Durbin-Watson:                   1.607
Prob(Omnibus):                  0.654   Jarque-Bera (JB):                0.639
Skew:                           0.372   Prob(JB):                        0.727
Kurtosis:                       2.758   Cond. No.                         817.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [56]:
results = sm.OLS(df['2021가격'], sm.add_constant(df['2021'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2021가격   R-squared:                       0.366
Model:                            OLS   Adj. R-squared:                  0.339
Method:                 Least Squares   F-statistic:                     13.29
Date:                Sun, 23 Apr 2023   Prob (F-statistic):            0.00135
Time:                        22:16:59   Log-Likelihood:                -179.69
No. Observations:                  25   AIC:                             363.4
Df Residuals:                      23   BIC:                             365.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        867.4999    154.265      5.623      0.000     548.378    1186.622
2021           1.4686      0.403      3.645      0.001       0.635       2.302
==============================================================================
Omnibus:                        1.647   Durbin-Watson:                   1.545
Prob(Omnibus):                  0.439   Jarque-Bera (JB):                1.468
Skew:                           0.530   Prob(JB):                        0.480
Kurtosis:                       2.465   Cond. No.                         885.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

---
---
---

### 4년 합친 것

In [57]:
crime_long = pd.melt(crime, id_vars=['자치구별'], var_name='year', value_name='crime_num')
crime_long

   자치구별  year  crime_num
0   종로구  2018        364
1    중구  2018        357
2   용산구  2018        417
3   성동구  2018        204
4   광진구  2018        363
..  ...   ...        ...
95  관악구  2021        528
96  서초구  2021        540
97  강남구  2021        946
98  송파구  2021        496
99  강동구  2021        234

[100 rows x 3 columns]

In [80]:
lst1=[i for i in df['2018가격']]
lst2=[i for i in df['2019가격']]
lst3=[i for i in df['2020가격']]
lst4=[i for i in df['2021가격']]

In [81]:
lst= lst1 + lst2 + lst3 + lst4

In [82]:
lst

[764.0,
 871.0,
 1200.0,
 1048.0,
 943.0,
 693.0,
 541.0,
 629.0,
 563.0,
 504.0,
 601.0,
 627.0,
 727.0,
 989.0,
 811.0,
 728.0,
 595.0,
 516.0,
 845.0,
 880.0,
 642.0,
 1461.0,
 1702.0,
 1201.0,
 858.0,
 1015.0,
 1024.0,
 1463.0,
 1245.0,
 1105.0,
 840.0,
 660.0,
 771.0,
 665.0,
 594.0,
 703.0,
 729.0,
 922.0,
 1221.0,
 1038.0,
 852.0,
 707.0,
 619.0,
 1039.0,
 1066.0,
 757.0,
 1755.0,
 2051.0,
 1440.0,
 1007.0,
 1034.0,
 1138.0,
 1594.0,
 1471.0,
 1291.0,
 995.0,
 760.0,
 914.0,
 771.0,
 675.0,
 844.0,
 827.0,
 1038.0,
 1344.0,
 1143.0,
 964.0,
 769.0,
 739.0,
 1180.0,
 1230.0,
 871.0,
 1913.0,
 2117.0,
 1601.0,
 1170.0,
 1239.0,
 1285.0,
 1903.0,
 1806.0,
 1517.0,
 1174.0,
 969.0,
 1144.0,
 939.0,
 899.0,
 1116.0,
 1042.0,
 1256.0,
 1568.0,
 1353.0,
 1175.0,
 945.0,
 914.0,
 1378.0,
 1670.0,
 1089.0,
 2208.0,
 2351.0,
 1983.0,
 1437.0]

In [83]:
crime_long['price'] = lst

In [84]:
crime_long

   자치구별  year  crime_num   price
0   종로구  2018        364   764.0
1    중구  2018        357   871.0
2   용산구  2018        417  1200.0
3   성동구  2018        204  1048.0
4   광진구  2018        363   943.0
..  ...   ...        ...     ...
95  관악구  2021        528  1089.0
96  서초구  2021        540  2208.0
97  강남구  2021        946  2351.0
98  송파구  2021        496  1983.0
99  강동구  2021        234  1437.0

[100 rows x 4 columns]

### 정규성

In [86]:
shapiro_test = stats.shapiro(df['2018'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.8547165989875793, pvalue=0.0021672924049198627)

### 상관분석

In [89]:
print(scipy.stats.spearmanr(crime_long['crime_num'], crime_long['price']))

SpearmanrResult(correlation=0.3787686032219969, pvalue=0.00010195618450325824)

### 회귀분석

In [90]:
results = sm.OLS(crime_long['price'], sm.add_constant(crime_long['crime_num'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.302
Model:                            OLS   Adj. R-squared:                  0.294
Method:                 Least Squares   F-statistic:                     42.32
Date:                Mon, 24 Apr 2023   Prob (F-statistic):           3.29e-09
Time:                        01:38:22   Log-Likelihood:                -724.65
No. Observations:                 100   AIC:                             1453.
Df Residuals:                      98   BIC:                             1459.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        676.1694     72.242      9.360      0.000     532.807     819.532
crime_num      1.1237      0.173      6.505      0.000       0.781       1.466
==============================================================================
Omnibus:                        7.952   Durbin-Watson:                   0.809
Prob(Omnibus):                  0.019   Jarque-Bera (JB):                7.804
Skew:                           0.676   Prob(JB):                       0.0202
Kurtosis:                       3.215   Cond. No.                         881.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""