In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:\\Windows\\Fonts\\malgun.ttf").get_name()
plt.rc("font", family=font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"] = False

import xml.etree.ElementTree as et

import urllib.request as req
import requests
import json

import urllib.request as req
from urllib.error import HTTPError, URLError 

from bs4 import BeautifulSoup

from urllib.request import urlopen

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import os
import re

from scipy.stats import shapiro
from scipy import stats
import scipy

# 범죄

In [2]:
crime = pd.read_csv('C:/acorn/midproject/crimerate/final_crime_gu_year.csv', index_col=0)
crime

    자치구별  2018  2019  2020  2021
0    종로구   364   370   272   271
1     중구   357   314   283   282
2    용산구   417   362   319   248
3    성동구   204   205   171   220
4    광진구   363   415   352   325
5   동대문구   243   249   244   282
6    중랑구   238   212   276   273
7    성북구   303   259   212   222
8    강북구   273   239   217   222
9    도봉구   177   136   131   131
10   노원구   293   272   236   293
11   은평구   312   283   251   293
12  서대문구   278   268   251   292
13   마포구   735   673   577   524
14   양천구   193   199   189   202
15   강서구   424   442   410   434
16   구로구   405   363   344   341
17   금천구   273   221   183   246
18  영등포구   592   520   484   480
19   동작구   416   367   305   304
20   관악구   545   579   557   528
21   서초구   635   785   578   540
22   강남구  1010  1280  1048   946
23   송파구   515   459   444   496
24   강동구   241   280   289   234

## 전월세가

In [4]:
buy2018 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2018_data.csv')
buy2018.drop(index=25, inplace=True)
buy2018.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2018가격'}, inplace=True)
buy2018 = buy2018[['자치구별', '2018가격']]
buy2018

    자치구별  2018가격
0    강남구   654.0
1    강동구   472.0
2    강북구   336.0
3    강서구   406.0
4    관악구   369.0
5    광진구   538.0
6    구로구   360.0
7    금천구   335.0
8    노원구   297.0
9    도봉구   276.0
10  동대문구   408.0
11   동작구   502.0
12   마포구   512.0
13  서대문구   436.0
14   서초구   645.0
15   성동구   542.0
16   성북구   407.0
17   송파구   577.0
18   양천구   494.0
19  영등포구   445.0
20   용산구   508.0
21   은평구   369.0
22   종로구   419.0
23    중구   482.0
24   중랑구   305.0

In [6]:
buy2019 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2019_data.csv')
buy2019.drop(index=25, inplace=True)
buy2019.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2019가격'}, inplace=True)
buy2019 = buy2019[['자치구별', '2019가격']]
buy2019

    자치구별  2019가격
0    강남구   676.0
1    강동구   471.0
2    강북구   339.0
3    강서구   442.0
4    관악구   380.0
5    광진구   546.0
6    구로구   362.0
7    금천구   346.0
8    노원구   304.0
9    도봉구   282.0
10  동대문구   423.0
11   동작구   499.0
12   마포구   536.0
13  서대문구   463.0
14   서초구   638.0
15   성동구   558.0
16   성북구   415.0
17   송파구   576.0
18   양천구   483.0
19  영등포구   478.0
20   용산구   532.0
21   은평구   395.0
22   종로구   538.0
23    중구   453.0
24   중랑구   370.0

In [7]:
buy2020 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2020_data.csv')
buy2020.drop(index=25, inplace=True)
buy2020.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2020가격'}, inplace=True)
buy2020 = buy2020[['자치구별', '2020가격']]
buy2020

    자치구별  2020가격
0    강남구   781.0
1    강동구   515.0
2    강북구   394.0
3    강서구   453.0
4    관악구   411.0
5    광진구   604.0
6    구로구   375.0
7    금천구   412.0
8    노원구   332.0
9    도봉구   314.0
10  동대문구   474.0
11   동작구   569.0
12   마포구   519.0
13  서대문구   499.0
14   서초구   760.0
15   성동구   618.0
16   성북구   462.0
17   송파구   647.0
18   양천구   527.0
19  영등포구   506.0
20   용산구   579.0
21   은평구   439.0
22   종로구   479.0
23    중구   549.0
24   중랑구   391.0

In [8]:
buy2021 = pd.read_csv('C:/acorn/MidtermProject/프로젝트/SeokwonNa/apt_rent_price_2018-22/save_point4_apt_rent_2021_data.csv')
buy2021.drop(index=25, inplace=True)
buy2021.rename(columns={'1m^2 전용면적당 거래금액(만원)':'2021가격'}, inplace=True)
buy2021 = buy2021[['자치구별', '2021가격']]
buy2021

    자치구별  2021가격
0    강남구   824.0
1    강동구   516.0
2    강북구   393.0
3    강서구   470.0
4    관악구   460.0
5    광진구   667.0
6    구로구   364.0
7    금천구   403.0
8    노원구   368.0
9    도봉구   355.0
10  동대문구   513.0
11   동작구   630.0
12   마포구   585.0
13  서대문구   533.0
14   서초구   796.0
15   성동구   658.0
16   성북구   497.0
17   송파구   672.0
18   양천구   535.0
19  영등포구   554.0
20   용산구   623.0
21   은평구   444.0
22   종로구   568.0
23    중구   566.0
24   중랑구   419.0

## 범죄&전월세가

In [9]:
from functools import reduce
import pandas as pd
dfs = [crime, buy2018, buy2019, buy2020, buy2021]
df = reduce(lambda left, right: pd.merge(left, right, on='자치구별'), dfs)
df

    자치구별  2018  2019  2020  2021  2018가격  2019가격  2020가격  2021가격
0    종로구   364   370   272   271   419.0   538.0   479.0   568.0
1     중구   357   314   283   282   482.0   453.0   549.0   566.0
2    용산구   417   362   319   248   508.0   532.0   579.0   623.0
3    성동구   204   205   171   220   542.0   558.0   618.0   658.0
4    광진구   363   415   352   325   538.0   546.0   604.0   667.0
5   동대문구   243   249   244   282   408.0   423.0   474.0   513.0
6    중랑구   238   212   276   273   305.0   370.0   391.0   419.0
7    성북구   303   259   212   222   407.0   415.0   462.0   497.0
8    강북구   273   239   217   222   336.0   339.0   394.0   393.0
9    도봉구   177   136   131   131   276.0   282.0   314.0   355.0
10   노원구   293   272   236   293   297.0   304.0   332.0   368.0
11   은평구   312   283   251   293   369.0   395.0   439.0   444.0
12  서대문구   278   268   251   292   436.0   463.0   499.0   533.0
13   마포구   735   673   577   524   512.0   536.0   519.0   585.0
14   양천구   193   199   189   202   494.0   483.0   527.0   535.0
15   강서구   424   442   410   434   406.0   442.0   453.0   470.0
16   구로구   405   363   344   341   360.0   362.0   375.0   364.0
17   금천구   273   221   183   246   335.0   346.0   412.0   403.0
18  영등포구   592   520   484   480   445.0   478.0   506.0   554.0
19   동작구   416   367   305   304   502.0   499.0   569.0   630.0
20   관악구   545   579   557   528   369.0   380.0   411.0   460.0
21   서초구   635   785   578   540   645.0   638.0   760.0   796.0
22   강남구  1010  1280  1048   946   654.0   676.0   781.0   824.0
23   송파구   515   459   444   496   577.0   576.0   647.0   672.0
24   강동구   241   280   289   234   472.0   471.0   515.0   516.0

In [11]:
df.to_csv('crime_rentprice_18-22.csv')

### 정규성

In [16]:
shapiro_test = stats.shapiro(df['2018'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.8547165989875793, pvalue=0.0021672924049198627)

In [13]:
shapiro_test = stats.shapiro(df['2019'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.7616845369338989, pvalue=5.567202242673375e-05)

In [14]:
shapiro_test = stats.shapiro(df['2020'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.7888317704200745, pvalue=0.00014889816520735621)

In [15]:
shapiro_test = stats.shapiro(df['2021'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.7921955585479736, pvalue=0.00016893752035684884)

### 상관분석

In [18]:
print(scipy.stats.spearmanr(df['2018'], df['2018가격'])) # p-value 어떻게 보는 것?
print(scipy.stats.spearmanr(df['2019'], df['2019가격']))
print(scipy.stats.spearmanr(df['2020'], df['2020가격']))
print(scipy.stats.spearmanr(df['2021'], df['2021가격'])) # 0.05보다 큼

SpearmanrResult(correlation=0.4717198922662562, pvalue=0.017284909254209294)
SpearmanrResult(correlation=0.5492307692307692, pvalue=0.00446140242603819)
SpearmanrResult(correlation=0.4420080866530011, pvalue=0.026948769450070537)
SpearmanrResult(correlation=0.37829523331919934, pvalue=0.06223471845916195)

In [19]:
corr = df.corr(method='spearman')
corr

,2018,2019,2020,2021,2018가격,2019가격,2020가격,2021가격
2018,1.000000,0.962877,0.894960,0.873942,0.471720,0.488171,0.408540,0.498942
2019,0.962877,1.000000,0.941335,0.900520,0.517023,0.549231,0.448462,0.543077
2020,0.894960,0.941335,1.000000,0.894342,0.513851,0.522023,0.442008,0.513945
2021,0.873942,0.900520,0.894342,1.000000,0.361239,0.370983,0.290937,0.378295
2018가격,0.471720,0.517023,0.513851,0.361239,1.000000,0.959031,0.983266,0.968263
2019가격,0.488171,0.549231,0.522023,0.370983,0.959031,1.000000,0.943077,0.974615
2020가격,0.408540,0.448462,0.442008,0.290937,0.983266,0.943077,1.000000,0.972308
2021가격,0.498942,0.543077,0.513945,0.378295,0.968263,0.974615,0.972308,1.000000

### 회귀분석

In [20]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(df['2018'].values.reshape(-1, 1), df['2018가격'].values.reshape(-1, 1))
lr.coef_[0]

array([0.31772277])

In [21]:
import statsmodels.api as sm
results = sm.OLS(df['2018가격'], sm.add_constant(df['2018'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2018가격   R-squared:                       0.358
Model:                            OLS   Adj. R-squared:                  0.330
Method:                 Least Squares   F-statistic:                     12.82
Date:                Sun, 23 Apr 2023   Prob (F-statistic):            0.00159
Time:                        22:24:56   Log-Likelihood:                -145.23
No. Observations:                  25   AIC:                             294.5
Df Residuals:                      23   BIC:                             296.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        319.1364     38.659      8.255      0.000     239.163     399.109
2018           0.3177      0.089      3.580      0.002       0.134       0.501
==============================================================================
Omnibus:                        3.355   Durbin-Watson:                   1.463
Prob(Omnibus):                  0.187   Jarque-Bera (JB):                1.553
Skew:                           0.240   Prob(JB):                        0.460
Kurtosis:                       1.877   Cond. No.                     1.00e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large,  1e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

- F-statistic의 p-value 값은 Prob(F-statistic)으로 표현되는데, 이는 0.05보다 작기에 이 회귀식은 회귀분석 모델 전체에 대해 통계적으로 의미가 있다고 볼 수 있습니다.

- 중간쯤에 보면 coef와 변수 x1의 p-value 값이 나와있습니다. 여기서 x1은 bmi이고 이 변수의 p-value가 0.000으로 표기 되어 있기에 0.05보다 작으므로 target을 설명하는데 유의하다고 판단할 수 있습니다.

In [22]:
results = sm.OLS(df['2019가격'], sm.add_constant(df['2019'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2019가격   R-squared:                       0.444
Model:                            OLS   Adj. R-squared:                  0.420
Method:                 Least Squares   F-statistic:                     18.39
Date:                Sun, 23 Apr 2023   Prob (F-statistic):           0.000274
Time:                        22:25:04   Log-Likelihood:                -142.96
No. Observations:                  25   AIC:                             289.9
Df Residuals:                      23   BIC:                             292.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        351.8109     29.574     11.896      0.000     290.632     412.990
2019           0.2779      0.065      4.289      0.000       0.144       0.412
==============================================================================
Omnibus:                        0.902   Durbin-Watson:                   1.311
Prob(Omnibus):                  0.637   Jarque-Bera (JB):                0.756
Skew:                          -0.042   Prob(JB):                        0.685
Kurtosis:                       2.152   Cond. No.                         879.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [23]:
results = sm.OLS(df['2020가격'], sm.add_constant(df['2020'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2020가격   R-squared:                       0.368
Model:                            OLS   Adj. R-squared:                  0.340
Method:                 Least Squares   F-statistic:                     13.36
Date:                Sun, 23 Apr 2023   Prob (F-statistic):            0.00132
Time:                        22:25:08   Log-Likelihood:                -148.46
No. Observations:                  25   AIC:                             300.9
Df Residuals:                      23   BIC:                             303.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        377.2214     39.695      9.503      0.000     295.106     459.337
2020           0.3686      0.101      3.656      0.001       0.160       0.577
==============================================================================
Omnibus:                        0.654   Durbin-Watson:                   1.755
Prob(Omnibus):                  0.721   Jarque-Bera (JB):                0.666
Skew:                           0.093   Prob(JB):                        0.717
Kurtosis:                       2.223   Cond. No.                         817.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
results = sm.OLS(df['2021가격'], sm.add_constant(df['2021'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 2021가격   R-squared:                       0.345
Model:                            OLS   Adj. R-squared:                  0.317
Method:                 Least Squares   F-statistic:                     12.12
Date:                Sun, 23 Apr 2023   Prob (F-statistic):            0.00202
Time:                        22:25:11   Log-Likelihood:                -150.73
No. Observations:                  25   AIC:                             305.5
Df Residuals:                      23   BIC:                             307.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        384.5240     48.425      7.941      0.000     284.350     484.698
2021           0.4404      0.126      3.482      0.002       0.179       0.702
==============================================================================
Omnibus:                        1.993   Durbin-Watson:                   1.413
Prob(Omnibus):                  0.369   Jarque-Bera (JB):                1.097
Skew:                           0.070   Prob(JB):                        0.578
Kurtosis:                       1.983   Cond. No.                         885.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

---
---
---

### 4년 합친 것

In [25]:
crime_long = pd.melt(crime, id_vars=['자치구별'], var_name='year', value_name='crime_num')
crime_long

   자치구별  year  crime_num
0   종로구  2018        364
1    중구  2018        357
2   용산구  2018        417
3   성동구  2018        204
4   광진구  2018        363
..  ...   ...        ...
95  관악구  2021        528
96  서초구  2021        540
97  강남구  2021        946
98  송파구  2021        496
99  강동구  2021        234

[100 rows x 3 columns]

In [26]:
lst1=[i for i in df['2018가격']]
lst2=[i for i in df['2019가격']]
lst3=[i for i in df['2020가격']]
lst4=[i for i in df['2021가격']]

In [27]:
lst= lst1 + lst2 + lst3 + lst4

In [28]:
crime_long['price'] = lst

In [30]:
crime_long

   자치구별  year  crime_num  price
0   종로구  2018        364  419.0
1    중구  2018        357  482.0
2   용산구  2018        417  508.0
3   성동구  2018        204  542.0
4   광진구  2018        363  538.0
..  ...   ...        ...    ...
95  관악구  2021        528  460.0
96  서초구  2021        540  796.0
97  강남구  2021        946  824.0
98  송파구  2021        496  672.0
99  강동구  2021        234  516.0

[100 rows x 4 columns]

### 정규성

In [32]:
shapiro_test = stats.shapiro(crime_long['crime_num'])
shapiro_test # 정규분포 아님

ShapiroResult(statistic=0.7994834184646606, pvalue=2.387267605818977e-10)

### 상관분석

In [33]:
print(scipy.stats.spearmanr(crime_long['crime_num'], crime_long['price']))

SpearmanrResult(correlation=0.3973607700219117, pvalue=4.2486395583882775e-05)

### 회귀분석

In [34]:
results = sm.OLS(crime_long['price'], sm.add_constant(crime_long['crime_num'])).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.285
Model:                            OLS   Adj. R-squared:                  0.277
Method:                 Least Squares   F-statistic:                     38.98
Date:                Mon, 24 Apr 2023   Prob (F-statistic):           1.10e-08
Time:                        01:42:49   Log-Likelihood:                -600.65
No. Observations:                 100   AIC:                             1205.
Df Residuals:                      98   BIC:                             1211.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        371.3297     20.905     17.763      0.000     329.844     412.815
crime_num      0.3121      0.050      6.244      0.000       0.213       0.411
==============================================================================
Omnibus:                        3.589   Durbin-Watson:                   1.115
Prob(Omnibus):                  0.166   Jarque-Bera (JB):                3.183
Skew:                           0.349   Prob(JB):                        0.204
Kurtosis:                       2.473   Cond. No.                         881.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""