## 출처: https://kosis.kr/statHtml/statHtml.do?orgId=135&tblId=TX_13501_A048&vw_cd=MT_ZTITLE&list_id=135_001_002_001&scrId=&seqNo=&lang_mode=ko&obj_var_id=&itm_id=&conn_path=MT_ZTITLE&path=%252FstatisticsList%252FstatisticsListIndex.do

In [130]:
import pandas as pd
import numpy as np
import re
import os

### 살인,강도,방화,성폭력

In [304]:
df = pd.read_csv('범죄.csv', encoding='euc-kr',header=2)
df

,발생지별(1),발생지별(2),소계,소계.1,소계.2,소계.3,살인,살인.1,살인.2,살인.3,...,강도.2,강도.3,방화,방화.1,방화.2,방화.3,성폭력,성폭력.1,성폭력.2,성폭력.3
0,발생지별(1),발생지별(2),2018,2019,2020,2021,2018,2019,2020,2021,...,2020,2021,2018,2019,2020,2021,2018,2019,2020,2021
1,서울,소계,9806,9752,8623,8629,152,146,157,127,...,143,125,292,251,217,185,9222,9206,8106,8192
2,서울,종로,364,370,272,271,7,4,8,5,...,7,4,9,8,6,3,345,350,251,259
3,서울,중구,357,314,283,282,2,5,2,6,...,5,6,15,10,13,10,329,293,263,260
4,서울,용산,417,362,319,248,1,3,5,3,...,6,1,12,9,5,7,401,344,303,237
5,서울,성동,204,205,171,220,2,6,5,4,...,3,4,7,2,1,10,192,188,162,202
6,서울,광진,363,415,352,325,7,4,2,5,...,4,4,6,7,7,6,347,398,339,310
7,서울,동대문,243,249,244,282,5,7,10,3,...,6,8,12,7,10,11,221,223,218,260
8,서울,중랑,238,212,276,273,4,10,10,4,...,5,6,8,15,9,8,223,183,252,255
9,서울,성북,303,259,212,222,8,3,4,4,...,3,2,10,10,5,9,284,243,200,207
10,서울,강북,273,239,217,222,8,6,9,4,...,4,2,10,4,9,6,248,227,195,210
11,서울,도봉,177,136,131,131,1,1,-,2,...,2,2,7,7,11,5,165,122,118,122
12,서울,노원,293,272,236,293,5,4,4,6,...,4,3,12,8,11,3,271,257,217,281
13,서울,은평,312,283,251,293,8,3,4,5,...,4,3,23,13,8,4,280,266,235,281
14,서울,서대문,278,268,251,292,5,2,15,3,...,2,2,10,9,12,8,260,252,222,279
15,서울,마포,735,673,577,524,6,2,8,7,...,4,4,5,5,8,9,718,664,557,504
16,서울,양천,193,199,189,202,2,7,5,1,...,3,3,14,7,11,5,173,180,170,193
17,서울,강서,424,442,410,434,11,8,10,9,...,7,2,18,24,12,11,389,406,381,412
18,서울,구로,405,363,344,341,8,10,7,5,...,5,3,15,8,11,4,373,341,321,329
19,서울,금천,273,221,183,246,5,6,4,7,...,7,3,8,9,9,7,255,194,163,229
20,서울,영등포,592,520,484,480,20,10,7,7,...,6,11,17,16,15,11,547,489,456,451
21,서울,동작,416,367,305,304,2,5,3,3,...,1,1,11,11,6,2,396,350,295,298
22,서울,관악,545,579,557,528,10,12,13,8,...,3,7,19,18,12,15,504,538,529,498
23,서울,서초,635,785,578,540,5,5,5,6,...,8,5,10,9,5,6,615,766,560,523
24,서울,강남,1010,1280,1048,946,12,9,6,13,...,15,25,11,8,8,12,973,1257,1019,896
25,서울,송파,515,459,444,496,5,8,8,3,...,13,9,11,14,9,9,493,428,414,475
26,서울,강동,241,280,289,234,3,6,3,4,...,16,5,12,13,4,4,220,247,266,221

In [305]:
df1=df[["발생지별(2)", "소계", "소계.1", "소계.2", "소계.3"]]

In [306]:
df1

    발생지별(2)    소계  소계.1  소계.2  소계.3
0   발생지별(2)  2018  2019  2020  2021
1        소계  9806  9752  8623  8629
2        종로   364   370   272   271
3        중구   357   314   283   282
4        용산   417   362   319   248
5        성동   204   205   171   220
6        광진   363   415   352   325
7       동대문   243   249   244   282
8        중랑   238   212   276   273
9        성북   303   259   212   222
10       강북   273   239   217   222
11       도봉   177   136   131   131
12       노원   293   272   236   293
13       은평   312   283   251   293
14      서대문   278   268   251   292
15       마포   735   673   577   524
16       양천   193   199   189   202
17       강서   424   442   410   434
18       구로   405   363   344   341
19       금천   273   221   183   246
20      영등포   592   520   484   480
21       동작   416   367   305   304
22       관악   545   579   557   528
23       서초   635   785   578   540
24       강남  1010  1280  1048   946
25       송파   515   459   444   496
26       강동   241   280   289   234

In [307]:
df1.columns = df1.loc[0]

In [308]:
df1.drop([0, 1], inplace=True)

C:\Users\khg08\AppData\Local\Temp\ipykernel_35572\526197053.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop([0, 1], inplace=True)

In [309]:
df1

0  발생지별(2)  2018  2019  2020  2021
2       종로   364   370   272   271
3       중구   357   314   283   282
4       용산   417   362   319   248
5       성동   204   205   171   220
6       광진   363   415   352   325
7      동대문   243   249   244   282
8       중랑   238   212   276   273
9       성북   303   259   212   222
10      강북   273   239   217   222
11      도봉   177   136   131   131
12      노원   293   272   236   293
13      은평   312   283   251   293
14     서대문   278   268   251   292
15      마포   735   673   577   524
16      양천   193   199   189   202
17      강서   424   442   410   434
18      구로   405   363   344   341
19      금천   273   221   183   246
20     영등포   592   520   484   480
21      동작   416   367   305   304
22      관악   545   579   557   528
23      서초   635   785   578   540
24      강남  1010  1280  1048   946
25      송파   515   459   444   496
26      강동   241   280   289   234

In [310]:
df1.rename(columns={'발생지별(2)':'자치구별'}, inplace=True)

C:\Users\khg08\AppData\Local\Temp\ipykernel_35572\1723660754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={'발생지별(2)':'자치구별'}, inplace=True)

In [311]:
df1.set_index('자치구별', inplace=True)

In [313]:
df1.to_csv('final_crime_gu_year.csv')