In [3]:
#데이터 출처: https://data.seoul.go.kr/dataList/OA-16095/S/1/datasetView.do

In [1]:
import numpy as np
import pandas as pd

In [2]:
#데이터 다운로드 후 utf-8로 변형시켜준다.
Seoul_CS1 = pd.read_csv("../../Data/JunkyuLee/Seoul_utf-8.csv")
Seoul_CS1

C:\Users\acorn\AppData\Local\Temp\ipykernel_6156\4115765318.py:2: DtypeWarning: Columns (13,24,36,38,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  Seoul_CS1 = pd.read_csv("../../Data/JunkyuLee/Seoul_utf-8.csv")

,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태코드,영업상태명,상세영업상태코드,상세영업상태명,폐업일자,휴업시작일자,...,공장판매직종업원수,공장생산직종업원수,건물소유구분명,보증액,월세액,다중이용업소여부,시설총규모,전통업소지정번호,전통업소주된음식,홈페이지
0,3130000,3130000-104-2022-00101,20220422,NaN,1,영업/정상,1,영업,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3000000,3000000-104-2022-00056,2022-04-22,NaN,1,영업/정상,1,영업,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3000000,3000000-104-2023-00015,2023-02-16,NaN,1,영업/정상,1,영업,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3240000,3240000-104-2023-00028,2023-02-16,NaN,1,영업/정상,1,영업,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3200000,3200000-104-2022-00154,2022-08-31,NaN,3,폐업,2,폐업,2023-03-24,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122979,3230000,3230000-104-2020-00399,20201224,NaN,1,영업/정상,1,영업,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122980,3200000,3200000-104-2020-00116,20200707,NaN,3,폐업,2,폐업,20230110,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122981,3150000,3150000-104-2018-00303,20181116,NaN,3,폐업,2,폐업,20230110,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122982,3230000,3230000-104-2018-00474,20181115,NaN,1,영업/정상,1,영업,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122983,3150000,3150000-104-2018-00256,20181015,NaN,1,영업/정상,1,영업,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# column 정리
Seoul_CS2 = Seoul_CS1[["인허가일자","영업상태코드","영업상태명","폐업일자", "업태구분명", "지번주소", "사업장명"]]
Seoul_CS2

,인허가일자,영업상태코드,영업상태명,폐업일자,업태구분명,지번주소,사업장명
0,20220422,1,영업/정상,NaN,커피숍,서울특별시 마포구 성산동 515 월드컵주경기장,팜스365
1,2022-04-22,1,영업/정상,NaN,기타 휴게음식점,서울특별시 종로구 숭인동 169 1층,메가엠지씨커피 종로숭인점
2,2023-02-16,1,영업/정상,NaN,커피숍,서울특별시 종로구 와룡동 109-1 UD빌딩 1층,노우즈 창덕
3,2023-02-16,1,영업/정상,NaN,편의점,서울특별시 강동구 천호동 335-8,세븐일레븐 천호이편한점
4,2022-08-31,3,폐업,2023-03-24,일반조리판매,서울특별시 관악구 신림동 1519-22,담다
...,...,...,...,...,...,...,...
122979,20201224,1,영업/정상,NaN,커피숍,서울특별시 송파구 장지동 897 위례중앙푸르지오1단지,디저트39 위례점
122980,20200707,3,폐업,20230110,일반조리판매,서울특별시 관악구 봉천동 928-1 우형빌딩,배달의쌀국수 관악점
122981,20181116,3,폐업,20230110,일반조리판매,서울특별시 강서구 마곡동 800-15 이너매스마곡Ⅱ 1층 112호,천년김밥
122982,20181115,1,영업/정상,NaN,기타 휴게음식점,서울특별시 송파구 삼전동 6-11,행복상점
122983,20181015,1,영업/정상,NaN,커피숍,서울특별시 강서구 화곡동 343-61 (지상 1층),메가엠지씨커피 까치산역점

In [4]:
#인허가일자와 폐업일자를 날짜 형식으로 바꾸면서 통일
Seoul_CS2["인허가일자"] = pd.to_datetime(Seoul_CS2["인허가일자"], format='%Y-%m-%d')
Seoul_CS2["폐업일자"] = pd.to_datetime(Seoul_CS2["폐업일자"], format='%Y-%m-%d', errors='coerce')
Seoul_CS2

C:\Users\acorn\AppData\Local\Temp\ipykernel_6156\1542180564.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Seoul_CS2["인허가일자"] = pd.to_datetime(Seoul_CS2["인허가일자"], format='%Y-%m-%d')
C:\Users\acorn\AppData\Local\Temp\ipykernel_6156\1542180564.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Seoul_CS2["폐업일자"] = pd.to_datetime(Seoul_CS2["폐업일자"], format='%Y-%m-%d', errors='coerce')

,인허가일자,영업상태코드,영업상태명,폐업일자,업태구분명,지번주소,사업장명
0,2022-04-22,1,영업/정상,NaT,커피숍,서울특별시 마포구 성산동 515 월드컵주경기장,팜스365
1,2022-04-22,1,영업/정상,NaT,기타 휴게음식점,서울특별시 종로구 숭인동 169 1층,메가엠지씨커피 종로숭인점
2,2023-02-16,1,영업/정상,NaT,커피숍,서울특별시 종로구 와룡동 109-1 UD빌딩 1층,노우즈 창덕
3,2023-02-16,1,영업/정상,NaT,편의점,서울특별시 강동구 천호동 335-8,세븐일레븐 천호이편한점
4,2022-08-31,3,폐업,2023-03-24,일반조리판매,서울특별시 관악구 신림동 1519-22,담다
...,...,...,...,...,...,...,...
122979,2020-12-24,1,영업/정상,NaT,커피숍,서울특별시 송파구 장지동 897 위례중앙푸르지오1단지,디저트39 위례점
122980,2020-07-07,3,폐업,2023-01-10,일반조리판매,서울특별시 관악구 봉천동 928-1 우형빌딩,배달의쌀국수 관악점
122981,2018-11-16,3,폐업,2023-01-10,일반조리판매,서울특별시 강서구 마곡동 800-15 이너매스마곡Ⅱ 1층 112호,천년김밥
122982,2018-11-15,1,영업/정상,NaT,기타 휴게음식점,서울특별시 송파구 삼전동 6-11,행복상점
122983,2018-10-15,1,영업/정상,NaT,커피숍,서울특별시 강서구 화곡동 343-61 (지상 1층),메가엠지씨커피 까치산역점

In [5]:
#편의점을 위해 컬럼을 정리한 데이터 csv로 저장
#Seoul_CS2.to_csv("../../Data/JunkyuLee/Seoul_col.csv")
#Seoul_CS2.to_csv("../../Data/JunkyuLee/Seoul_col_euc-kr.csv", encoding="euc-kr")

In [6]:
# 인허가일자 기준으로 정렬
Seoul_CS2 = pd.read_csv("../../Data/JunkyuLee/Seoul_col.csv", index_col=0)
Seoul_CS2 = Seoul_CS2.sort_values("인허가일자")
Seoul_CS2

,인허가일자,영업상태코드,영업상태명,폐업일자,업태구분명,지번주소,사업장명
75246,1900-08-12,3,폐업,1995-08-21,다방,서울특별시 구로구 구로동 716-10번지,청자
94058,1904-08-08,3,폐업,1994-07-05,다방,서울특별시 서초구 방배동 777-20번지,피터팬
116013,1904-08-08,3,폐업,1993-12-31,패스트푸드,서울특별시 송파구 잠실동 228-9번지,코리아세븐
41577,1909-03-12,3,폐업,1994-06-20,과자점,서울특별시 성북구 동선동2가 165번지,뺑뜨비성신여대분점
78991,1913-09-16,1,영업/정상,NaN,다방,서울특별시 영등포구 여의도동 24-2번지 102호,린네스가든
...,...,...,...,...,...,...,...
1601,2023-04-07,1,영업/정상,NaN,커피숍,서울특별시 영등포구 당산동1가 53-2,카페 유어데이(Your day)
1602,2023-04-07,1,영업/정상,NaN,기타 휴게음식점,서울특별시 영등포구 양평동4가 68-1 대명빌딩,긱스타 PC방
1603,2023-04-07,1,영업/정상,NaN,커피숍,서울특별시 영등포구 여의도동 25-2,주식회사 더치프레소
1590,2023-04-07,1,영업/정상,NaN,기타 휴게음식점,서울특별시 서대문구 충정로2가 185-15 충정로현대아파트 2층 202호,원투고홈
1593,2023-04-07,1,영업/정상,NaN,커피숍,서울특별시 마포구 아현동 662 마포 더 클래시,더벤티 마포더클래시점

In [7]:
Seoul_CS2["업태구분명"].unique()

array(['다방', '패스트푸드', '과자점', '백화점', '편의점', '일반조리판매', '기타 휴게음식점', '커피숍',
       '공항', '유원지', '관광호텔', '철도역구내', '전통찻집', '고속도로', '?球北떳?판매', '아이스크림',
       '단란주점', '김밥(도시락)', '198366.89122772     ', '198358.566988241    ',
       '208589.363343145    ', '키즈카페', '기타', '203811.366422118    ',
       '202466.119176743    ', '호프/통닭', '푸드트럭', '떡카페', '극장', '룸살롱',
       '202520.972243984', '한식'], dtype=object)

In [8]:
#커피숍과 다방만 추출
Seoul_CS3 = Seoul_CS2[Seoul_CS2["업태구분명"].isin(["커피숍", "다방"])]
Seoul_CS3

,인허가일자,영업상태코드,영업상태명,폐업일자,업태구분명,지번주소,사업장명
75246,1900-08-12,3,폐업,1995-08-21,다방,서울특별시 구로구 구로동 716-10번지,청자
94058,1904-08-08,3,폐업,1994-07-05,다방,서울특별시 서초구 방배동 777-20번지,피터팬
78991,1913-09-16,1,영업/정상,NaN,다방,서울특별시 영등포구 여의도동 24-2번지 102호,린네스가든
55254,1931-11-06,3,폐업,1997-03-11,다방,서울특별시 서대문구 충정로3가 32-10번지,터틀
104726,1931-12-17,3,폐업,1996-05-06,다방,서울특별시 강남구 논현동 4-21번지,자뎅커피타운본점
...,...,...,...,...,...,...,...
1595,2023-04-07,1,영업/정상,NaN,커피숍,서울특별시 마포구 도화동 559 마포트라팰리스,더벤티 마포트라팰리스점
1597,2023-04-07,1,영업/정상,NaN,커피숍,서울특별시 강동구 길동 391-5,빽다방 길동역점
1601,2023-04-07,1,영업/정상,NaN,커피숍,서울특별시 영등포구 당산동1가 53-2,카페 유어데이(Your day)
1603,2023-04-07,1,영업/정상,NaN,커피숍,서울특별시 영등포구 여의도동 25-2,주식회사 더치프레소
1593,2023-04-07,1,영업/정상,NaN,커피숍,서울특별시 마포구 아현동 662 마포 더 클래시,더벤티 마포더클래시점

In [9]:
#서울시 구 리스트 생성
gu_list = []
for i in Seoul_CS3["지번주소"].str.split().str[1].unique()[:-1]:
    gu_list.append(i)
print(gu_list, end=" ")

['구로구', '서초구', '영등포구', '서대문구', '강남구', '중구', '송파구', '종로구', '마포구', '성북구', '동대문구', '용산구', '중랑구', '강북구', '동작구', '은평구', '강서구', '강동구', '도봉구', '금천구', '양천구', '관악구', '노원구', '성동구', '광진구']

In [10]:
# 월별 마지막날 리스트 생성
import calendar

Date = []
for year in range(2017, 2023):  # 2017년부터 2022년까지 반복
    for month in range(1, 13):  # 1월부터 12월까지 반복
        last_day = calendar.monthrange(year, month)[1]  # 각 달의 마지막 날짜
        Date.append(f"{year}-{month}-{last_day}")
print(Date, end=" ")

['2017-1-31', '2017-2-28', '2017-3-31', '2017-4-30', '2017-5-31', '2017-6-30', '2017-7-31', '2017-8-31', '2017-9-30', '2017-10-31', '2017-11-30', '2017-12-31', '2018-1-31', '2018-2-28', '2018-3-31', '2018-4-30', '2018-5-31', '2018-6-30', '2018-7-31', '2018-8-31', '2018-9-30', '2018-10-31', '2018-11-30', '2018-12-31', '2019-1-31', '2019-2-28', '2019-3-31', '2019-4-30', '2019-5-31', '2019-6-30', '2019-7-31', '2019-8-31', '2019-9-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-1-31', '2020-2-29', '2020-3-31', '2020-4-30', '2020-5-31', '2020-6-30', '2020-7-31', '2020-8-31', '2020-9-30', '2020-10-31', '2020-11-30', '2020-12-31', '2021-1-31', '2021-2-28', '2021-3-31', '2021-4-30', '2021-5-31', '2021-6-30', '2021-7-31', '2021-8-31', '2021-9-30', '2021-10-31', '2021-11-30', '2021-12-31', '2022-1-31', '2022-2-28', '2022-3-31', '2022-4-30', '2022-5-31', '2022-6-30', '2022-7-31', '2022-8-31', '2022-9-30', '2022-10-31', '2022-11-30', '2022-12-31']

In [11]:
#월별 마지막 날 기준으로 구별 커피숍 개수 파악 후 데이터 프레임 생성
df = pd.DataFrame(index=gu_list, columns=Date)
for i, gu in enumerate(gu_list):
    print(gu)
    for j, D in enumerate(Date):
        gu_date = Seoul_CS3[(Seoul_CS3["지번주소"].astype(str).str.split(" ").str[1]==gu) & (Seoul_CS3["인허가일자"] <= D) & ((Seoul_CS3["폐업일자"] >= D) | Seoul_CS3["폐업일자"].isnull())]
        count = len(gu_date)
        df.iloc[i, j] = count
        print(count)

구로구
399
404
404
404
404
404
404
404
404
399
401
404
407
405
405
405
405
405
405
405
405
407
409
407
408
414
414
414
414
414
414
414
414
414
412
414
454
458
458
458
458
458
458
458
458
457
460
459
473
472
472
472
472
472
472
472
472
477
475
474
488
488
488
488
488
488
488
488
488
490
491
488
서초구
921
926
926
926
926
926
926
926
926
925
929
929
942
943
943
943
943
943
943
943
943
953
952
949
958
967
967
967
967
967
967
967
967
970
971
974
1006
1005
1005
1005
1005
1005
1005
1005
1005
1007
1006
1005
1022
1002
1002
1002
1002
1002
1002
1002
1002
1015
1018
1004
1008
1012
1012
1012
1012
1012
1012
1012
1012
1014
1012
1012
영등포구
753
766
766
766
766
766
766
766
766
754
760
766
807
798
798
798
798
798
798
798
798
805
804
799
827
843
843
843
843
843
843
843
843
835
839
844
874
862
862
862
862
862
862
862
862
873
877
864
902
914
914
914
914
914
914
914
914
907
913
916
905
899
899
899
899
899
899
899
899
903
901
899
서대문구
441
447
447
447
447
447
447
447
447
443
448
448
477
492
492
492
492
492
492
492
492
480
485
492
524
524
524
524
524
524
524
524
524
524
520
525
546
521
521
521
521
521
521
521
521
544
539
522
481
494
494
494
494
494
494
494
494
486
492
496
516
496
496
496
496
496
496
496
496
513
517
496
강남구
1586
1586
1586
1586
1586
1586
1586
1586
1586
1585
1590
1589
1674
1675
1675
1675
1675
1675
1675
1675
1675
1686
1675
1679
1789
1793
1793
1793
1793
1793
1793
1793
1793
1801
1798
1794
1842
1831
1831
1831
1831
1831
1831
1831
1831
1843
1844
1834
1870
1873
1873
1873
1873
1873
1873
1873
1873
1871
1881
1873
1900
1882
1882
1882
1882
1882
1882
1882
1882
1907
1892
1883
중구
1016
1034
1034
1034
1034
1034
1034
1034
1034
1021
1026
1034
1054
1072
1072
1072
1072
1072
1072
1072
1072
1066
1070
1072
1122
1135
1135
1135
1135
1135
1135
1135
1135
1127
1134
1135
1149
1148
1148
1148
1148
1148
1148
1148
1148
1148
1149
1149
1150
1147
1147
1147
1147
1147
1147
1147
1147
1151
1150
1148
1168
1166
1166
1166
1166
1166
1166
1166
1166
1168
1164
1166
송파구
428
440
440
440
440
440
440
440
440
431
437
440
476
441
441
441
441
441
441
441
441
473
450
445
453
476
476
476
476
476
476
476
476
458
465
476
567
585
585
585
585
585
585
585
585
569
582
585
676
692
692
692
692
692
692
692
692
683
695
692
771
792
792
792
792
792
792
792
792
788
785
792
종로구
830
838
838
838
838
838
838
838
838
831
837
838
869
876
876
876
876
876
876
876
876
866
871
877
906
895
895
895
895
895
895
895
895
899
899
896
882
859
859
859
859
859
859
859
859
878
878
862
848
850
850
850
850
850
850
850
850
849
848
850
879
873
873
873
873
873
873
873
873
877
874
873
마포구
908
916
916
916
916
916
916
916
916
911
915
916
964
941
941
941
941
941
941
941
941
966
958
943
871
851
851
851
851
851
851
851
851
867
860
851
779
755
755
755
755
755
755
755
755
773
763
755
865
906
906
906
906
906
906
906
906
875
893
906
912
930
930
930
930
930
930
930
930
921
917
930
성북구
380
391
391
391
391
391
391
391
391
382
388
391
426
431
431
431
431
431
431
431
431
429
433
433
444
453
453
453
453
453
453
453
453
447
452
455
481
492
492
492
492
492
492
492
492
487
495
492
508
524
524
524
524
524
524
524
524
512
515
524
555
559
559
559
559
559
559
559
559
559
565
559
동대문구
351
346
346
346
346
346
346
346
346
350
348
346
379
395
395
395
395
395
395
395
395
388
392
395
405
408
408
408
408
408
408
408
408
406
411
408
422
424
424
424
424
424
424
424
424
420
421
424
423
427
427
427
427
427
427
427
427
425
424
427
412
403
403
403
403
403
403
403
403
412
414
403
용산구
370
379
379
379
379
379
379
379
379
370
378
379
390
391
391
391
391
391
391
391
391
391
394
391
417
420
420
420
420
420
420
420
420
420
421
422
440
444
444
444
444
444
444
444
444
440
443
444
443
447
447
447
447
447
447
447
447
444
450
449
469
480
480
480
480
480
480
480
480
472
482
480
중랑구
237
234
234
234
234
234
234
234
234
239
239
234
250
246
246
246
246
246
246
246
246
250
250
247
290
295
295
295
295
295
295
295
295
294
297
296
329
329
329
329
329
329
329
329
329
326
328
329
361
367
367
367
367
367
367
367
367
362
370
367
382
377
377
377
377
377
377
377
377
381
380
377
강북구
202
203
203
203
203
203
203
203
203
203
204
203
212
211
211
211
211
211
211
211
211
215
216
211
217
219
219
219
219
219
219
219
219
218
222
221
240
243
243
243
243
243
243
243
243
238
240
243
239
251
251
251
251
251
251
251
251
248
253
251
249
239
239
239
239
239
239
239
239
247
246
239
동작구
389
397
397
397
397
397
397
397
397
393
398
397
414
416
416
416
416
416
416
416
416
415
420
416
444
438
438
438
438
438
438
438
438
441
440
439
461
431
431
431
431
431
431
431
431
465
470
432
441
452
452
452
452
452
452
452
452
448
453
453
472
465
465
465
465
465
465
465
465
469
466
465
은평구
347
352
352
352
352
352
352
352
352
349
355
352
379
387
387
387
387
387
387
387
387
387
388
387
374
367
367
367
367
367
367
367
367
378
372
368
385
399
399
399
399
399
399
399
399
390
398
400
415
408
408
408
408
408
408
408
408
411
410
408
391
379
379
379
379
379
379
379
379
390
385
379
강서구
649
665
665
665
665
665
665
665
665
650
662
665
728
748
748
748
748
748
748
748
748
742
747
748
827
838
838
838
838
838
838
838
838
843
845
842
900
907
907
907
907
907
907
907
907
906
911
907
990
983
983
983
983
983
983
983
983
994
996
984
1026
1004
1004
1004
1004
1004
1004
1004
1004
1027
1021
1004
강동구
388
383
383
383
383
383
383
383
383
380
384
383
417
414
414
414
414
414
414
414
414
419
414
416
460
470
470
470
470
470
470
470
470
461
468
471
519
516
516
516
516
516
516
516
516
519
519
517
574
578
578
578
578
578
578
578
578
581
577
579
617
608
608
608
608
608
608
608
608
622
615
608
도봉구
198
199
199
199
199
199
199
199
199
203
203
199
226
228
228
228
228
228
228
228
228
227
227
229
247
249
249
249
249
249
249
249
249
249
247
249
271
272
272
272
272
272
272
272
272
276
277
273
284
280
280
280
280
280
280
280
280
285
283
281
287
274
274
274
274
274
274
274
274
279
278
275
금천구
293
289
289
289
289
289
289
289
289
289
288
289
311
323
323
323
323
323
323
323
323
314
324
324
340
337
337
337
337
337
337
337
337
339
340
339
368
375
375
375
375
375
375
375
375
367
373
375
404
398
398
398
398
398
398
398
398
396
403
400
423
423
423
423
423
423
423
423
423
428
431
423
양천구
369
352
352
352
352
352
352
352
352
364
358
352
357
356
356
356
356
356
356
356
356
355
358
357
380
391
391
391
391
391
391
391
391
387
393
392
421
414
414
414
414
414
414
414
414
419
420
415
418
424
424
424
424
424
424
424
424
420
424
425
436
442
442
442
442
442
442
442
442
438
442
442
관악구
429
436
436
436
436
436
436
436
436
430
433
436
471
479
479
479
479
479
479
479
479
472
477
479
527
527
527
527
527
527
527
527
527
523
525
527
562
559
559
559
559
559
559
559
559
561
561
559
584
593
593
593
593
593
593
593
593
586
593
593
606
594
594
594
594
594
594
594
594
605
600
594
노원구
391
399
399
399
399
399
399
399
399
396
398
399
427
432
432
432
432
432
432
432
432
429
431
433
472
472
472
472
472
472
472
472
472
473
477
475
489
484
484
484
484
484
484
484
484
489
486
484
517
523
523
523
523
523
523
523
523
519
521
523
556
545
545
545
545
545
545
545
545
554
550
546
성동구
290
299
299
299
299
299
299
299
299
295
299
299
336
344
344
344
344
344
344
344
344
337
339
344
364
383
383
383
383
383
383
383
383
368
380
383
421
421
421
421
421
421
421
421
421
420
416
422
434
436
436
436
436
436
436
436
436
437
441
437
450
439
439
439
439
439
439
439
439
456
443
439
광진구
300
302
302
302
302
302
302
302
302
301
298
302
357
374
374
374
374
374
374
374
374
365
370
374
437
443
443
443
443
443
443
443
443
443
443
443
500
501
501
501
501
501
501
501
501
503
505
503
548
550
550
550
550
550
550
550
550
555
557
551
599
580
580
580
580
580
580
580
580
590
589
580

In [12]:
# 시각화를 위해 데이터를 숫자형으로 변경
df = df.astype("int64")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 구로구 to 광진구
Data columns (total 72 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   2017-1-31   25 non-null     int64
 1   2017-2-28   25 non-null     int64
 2   2017-3-31   25 non-null     int64
 3   2017-4-30   25 non-null     int64
 4   2017-5-31   25 non-null     int64
 5   2017-6-30   25 non-null     int64
 6   2017-7-31   25 non-null     int64
 7   2017-8-31   25 non-null     int64
 8   2017-9-30   25 non-null     int64
 9   2017-10-31  25 non-null     int64
 10  2017-11-30  25 non-null     int64
 11  2017-12-31  25 non-null     int64
 12  2018-1-31   25 non-null     int64
 13  2018-2-28   25 non-null     int64
 14  2018-3-31   25 non-null     int64
 15  2018-4-30   25 non-null     int64
 16  2018-5-31   25 non-null     int64
 17  2018-6-30   25 non-null     int64
 18  2018-7-31   25 non-null     int64
 19  2018-8-31   25 non-null     int64
 20  2018-9-30   25 non-null     int64
 21  2018-10-31  25 non-null     int64
 22  2018-11-30  25 non-null     int64
 23  2018-12-31  25 non-null     int64
 24  2019-1-31   25 non-null     int64
 25  2019-2-28   25 non-null     int64
 26  2019-3-31   25 non-null     int64
 27  2019-4-30   25 non-null     int64
 28  2019-5-31   25 non-null     int64
 29  2019-6-30   25 non-null     int64
 30  2019-7-31   25 non-null     int64
 31  2019-8-31   25 non-null     int64
 32  2019-9-30   25 non-null     int64
 33  2019-10-31  25 non-null     int64
 34  2019-11-30  25 non-null     int64
 35  2019-12-31  25 non-null     int64
 36  2020-1-31   25 non-null     int64
 37  2020-2-29   25 non-null     int64
 38  2020-3-31   25 non-null     int64
 39  2020-4-30   25 non-null     int64
 40  2020-5-31   25 non-null     int64
 41  2020-6-30   25 non-null     int64
 42  2020-7-31   25 non-null     int64
 43  2020-8-31   25 non-null     int64
 44  2020-9-30   25 non-null     int64
 45  2020-10-31  25 non-null     int64
 46  2020-11-30  25 non-null     int64
 47  2020-12-31  25 non-null     int64
 48  2021-1-31   25 non-null     int64
 49  2021-2-28   25 non-null     int64
 50  2021-3-31   25 non-null     int64
 51  2021-4-30   25 non-null     int64
 52  2021-5-31   25 non-null     int64
 53  2021-6-30   25 non-null     int64
 54  2021-7-31   25 non-null     int64
 55  2021-8-31   25 non-null     int64
 56  2021-9-30   25 non-null     int64
 57  2021-10-31  25 non-null     int64
 58  2021-11-30  25 non-null     int64
 59  2021-12-31  25 non-null     int64
 60  2022-1-31   25 non-null     int64
 61  2022-2-28   25 non-null     int64
 62  2022-3-31   25 non-null     int64
 63  2022-4-30   25 non-null     int64
 64  2022-5-31   25 non-null     int64
 65  2022-6-30   25 non-null     int64
 66  2022-7-31   25 non-null     int64
 67  2022-8-31   25 non-null     int64
 68  2022-9-30   25 non-null     int64
 69  2022-10-31  25 non-null     int64
 70  2022-11-30  25 non-null     int64
 71  2022-12-31  25 non-null     int64
dtypes: int64(72)
memory usage: 14.3+ KB

In [13]:
# 다른 데이터와의 merge를 위해 index name 설정
df.index.name="자치구별"

In [14]:
df

,2017-1-31,2017-2-28,2017-3-31,2017-4-30,2017-5-31,2017-6-30,2017-7-31,2017-8-31,2017-9-30,2017-10-31,...,2022-3-31,2022-4-30,2022-5-31,2022-6-30,2022-7-31,2022-8-31,2022-9-30,2022-10-31,2022-11-30,2022-12-31
자치구별,,,,,,,,,,,,,,,,,,,,,
구로구,399,404,404,404,404,404,404,404,404,399,...,488,488,488,488,488,488,488,490,491,488
서초구,921,926,926,926,926,926,926,926,926,925,...,1012,1012,1012,1012,1012,1012,1012,1014,1012,1012
영등포구,753,766,766,766,766,766,766,766,766,754,...,899,899,899,899,899,899,899,903,901,899
서대문구,441,447,447,447,447,447,447,447,447,443,...,496,496,496,496,496,496,496,513,517,496
강남구,1586,1586,1586,1586,1586,1586,1586,1586,1586,1585,...,1882,1882,1882,1882,1882,1882,1882,1907,1892,1883
중구,1016,1034,1034,1034,1034,1034,1034,1034,1034,1021,...,1166,1166,1166,1166,1166,1166,1166,1168,1164,1166
송파구,428,440,440,440,440,440,440,440,440,431,...,792,792,792,792,792,792,792,788,785,792
종로구,830,838,838,838,838,838,838,838,838,831,...,873,873,873,873,873,873,873,877,874,873
마포구,908,916,916,916,916,916,916,916,916,911,...,930,930,930,930,930,930,930,921,917,930
성북구,380,391,391,391,391,391,391,391,391,382,...,559,559,559,559,559,559,559,559,565,559
동대문구,351,346,346,346,346,346,346,346,346,350,...,403,403,403,403,403,403,403,412,414,403
용산구,370,379,379,379,379,379,379,379,379,370,...,480,480,480,480,480,480,480,472,482,480
중랑구,237,234,234,234,234,234,234,234,234,239,...,377,377,377,377,377,377,377,381,380,377
강북구,202,203,203,203,203,203,203,203,203,203,...,239,239,239,239,239,239,239,247,246,239
동작구,389,397,397,397,397,397,397,397,397,393,...,465,465,465,465,465,465,465,469,466,465
은평구,347,352,352,352,352,352,352,352,352,349,...,379,379,379,379,379,379,379,390,385,379
강서구,649,665,665,665,665,665,665,665,665,650,...,1004,1004,1004,1004,1004,1004,1004,1027,1021,1004
강동구,388,383,383,383,383,383,383,383,383,380,...,608,608,608,608,608,608,608,622,615,608
도봉구,198,199,199,199,199,199,199,199,199,203,...,274,274,274,274,274,274,274,279,278,275
금천구,293,289,289,289,289,289,289,289,289,289,...,423,423,423,423,423,423,423,428,431,423
양천구,369,352,352,352,352,352,352,352,352,364,...,442,442,442,442,442,442,442,438,442,442
관악구,429,436,436,436,436,436,436,436,436,430,...,594,594,594,594,594,594,594,605,600,594
노원구,391,399,399,399,399,399,399,399,399,396,...,545,545,545,545,545,545,545,554,550,546
성동구,290,299,299,299,299,299,299,299,299,295,...,439,439,439,439,439,439,439,456,443,439
광진구,300,302,302,302,302,302,302,302,302,301,...,580,580,580,580,580,580,580,590,589,580

In [15]:
#생성된 데이터 프레임 파일로 저장
df.to_csv("../../Data/JunkyuLee/gu_month_coffee.csv")
df.to_csv("../../Data/JunkyuLee/gu_month_coffee_euc-kr.csv", encoding="EUC-KR")

In [16]:
#매해 마지막 날 리스트 생성
import calendar

Date = []
for year in range(2017, 2023):  # 2017년부터 2022년까지 반복
    last_day = calendar.monthrange(year, 12)[1]  # 각 해의 마지막 날짜
    Date.append(f"{year}-{month}-{last_day}")
print(Date, end=" ")

['2017-12-31', '2018-12-31', '2019-12-31', '2020-12-31', '2021-12-31', '2022-12-31']

In [17]:
#매해 마지막 날 기준으로 구별 커피숍 개수 파악 후 데이터 프레임 생성 
df_year = pd.DataFrame(index=gu_list, columns=Date)
for i, gu in enumerate(gu_list):
    print(gu)
    for j, D in enumerate(Date):
        gu_date = Seoul_CS3[(Seoul_CS3["지번주소"].astype(str).str.split(" ").str[1]==gu) & (Seoul_CS3["인허가일자"] <= D) & ((Seoul_CS3["폐업일자"] >= D) | Seoul_CS3["폐업일자"].isnull())]
        count = len(gu_date)
        df_year.iloc[i, j] = count
        print(count)

구로구
404
407
414
459
474
488
서초구
929
949
974
1005
1004
1012
영등포구
766
799
844
864
916
899
서대문구
448
492
525
522
496
496
강남구
1589
1679
1794
1834
1873
1883
중구
1034
1072
1135
1149
1148
1166
송파구
440
445
476
585
692
792
종로구
838
877
896
862
850
873
마포구
916
943
851
755
906
930
성북구
391
433
455
492
524
559
동대문구
346
395
408
424
427
403
용산구
379
391
422
444
449
480
중랑구
234
247
296
329
367
377
강북구
203
211
221
243
251
239
동작구
397
416
439
432
453
465
은평구
352
387
368
400
408
379
강서구
665
748
842
907
984
1004
강동구
383
416
471
517
579
608
도봉구
199
229
249
273
281
275
금천구
289
324
339
375
400
423
양천구
352
357
392
415
425
442
관악구
436
479
527
559
593
594
노원구
399
433
475
484
523
546
성동구
299
344
383
422
437
439
광진구
302
374
443
503
551
580

In [18]:
df_year

     2017-12-31 2018-12-31 2019-12-31 2020-12-31 2021-12-31 2022-12-31
구로구         404        407        414        459        474        488
서초구         929        949        974       1005       1004       1012
영등포구        766        799        844        864        916        899
서대문구        448        492        525        522        496        496
강남구        1589       1679       1794       1834       1873       1883
중구         1034       1072       1135       1149       1148       1166
송파구         440        445        476        585        692        792
종로구         838        877        896        862        850        873
마포구         916        943        851        755        906        930
성북구         391        433        455        492        524        559
동대문구        346        395        408        424        427        403
용산구         379        391        422        444        449        480
중랑구         234        247        296        329        367        377
강북구         203        211        221        243        251        239
동작구         397        416        439        432        453        465
은평구         352        387        368        400        408        379
강서구         665        748        842        907        984       1004
강동구         383        416        471        517        579        608
도봉구         199        229        249        273        281        275
금천구         289        324        339        375        400        423
양천구         352        357        392        415        425        442
관악구         436        479        527        559        593        594
노원구         399        433        475        484        523        546
성동구         299        344        383        422        437        439
광진구         302        374        443        503        551        580

In [19]:
# column 변경을 위해 년도만 추출하여 리스트 생성
year = []
for i in pd.Series(df_year.columns).str.split("-"):
    year.append(i[0])
print(year)

['2017', '2018', '2019', '2020', '2021', '2022']

In [20]:
# column을 년도로 변경
df_year.columns=year
df_year

      2017  2018  2019  2020  2021  2022
구로구    404   407   414   459   474   488
서초구    929   949   974  1005  1004  1012
영등포구   766   799   844   864   916   899
서대문구   448   492   525   522   496   496
강남구   1589  1679  1794  1834  1873  1883
중구    1034  1072  1135  1149  1148  1166
송파구    440   445   476   585   692   792
종로구    838   877   896   862   850   873
마포구    916   943   851   755   906   930
성북구    391   433   455   492   524   559
동대문구   346   395   408   424   427   403
용산구    379   391   422   444   449   480
중랑구    234   247   296   329   367   377
강북구    203   211   221   243   251   239
동작구    397   416   439   432   453   465
은평구    352   387   368   400   408   379
강서구    665   748   842   907   984  1004
강동구    383   416   471   517   579   608
도봉구    199   229   249   273   281   275
금천구    289   324   339   375   400   423
양천구    352   357   392   415   425   442
관악구    436   479   527   559   593   594
노원구    399   433   475   484   523   546
성동구    299   344   383   422   437   439
광진구    302   374   443   503   551   580

In [21]:
# 시각화를 위해 모든 데이터를 숫자 데이터로 변경
df_year = df_year[:].astype("int64")
df_year.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 구로구 to 광진구
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2017    25 non-null     int64
 1   2018    25 non-null     int64
 2   2019    25 non-null     int64
 3   2020    25 non-null     int64
 4   2021    25 non-null     int64
 5   2022    25 non-null     int64
dtypes: int64(6)
memory usage: 1.4+ KB

In [22]:
# 다른 데이터와의 merge를 위해 index name 설정
df_year.index.name="자치구별"

In [23]:
df_year

      2017  2018  2019  2020  2021  2022
자치구별
구로구    404   407   414   459   474   488
서초구    929   949   974  1005  1004  1012
영등포구   766   799   844   864   916   899
서대문구   448   492   525   522   496   496
강남구   1589  1679  1794  1834  1873  1883
중구    1034  1072  1135  1149  1148  1166
송파구    440   445   476   585   692   792
종로구    838   877   896   862   850   873
마포구    916   943   851   755   906   930
성북구    391   433   455   492   524   559
동대문구   346   395   408   424   427   403
용산구    379   391   422   444   449   480
중랑구    234   247   296   329   367   377
강북구    203   211   221   243   251   239
동작구    397   416   439   432   453   465
은평구    352   387   368   400   408   379
강서구    665   748   842   907   984  1004
강동구    383   416   471   517   579   608
도봉구    199   229   249   273   281   275
금천구    289   324   339   375   400   423
양천구    352   357   392   415   425   442
관악구    436   479   527   559   593   594
노원구    399   433   475   484   523   546
성동구    299   344   383   422   437   439
광진구    302   374   443   503   551   580

In [24]:
# 년도별, 구별 커피숍 개수 파일 저장
df_year.to_csv("../../Data/JunkyuLee/gu_year_coffee.csv")
df_year.to_csv("../../Data/JunkyuLee/gu_year_coffee_euc-kr.csv", encoding="EUC-KR")