# 학원데이터
## 입시검정 및 보습학원, 국제화 학원, 예능, 특수교육학원 데이터
    - 데이터 출처 : https://data.seoul.go.kr/dataList/195/S/2/datasetView.do

In [1]:
import pandas as pd

In [19]:
a=pd.read_csv("C:\\Users\\owner\\team project\\raw data\\사설학원+및+독서실(2009년+이후)_20230418145558.csv")

In [20]:
a.head(10)

,자치구별(1),자치구별(2),2018,2018.1,2018.2,2018.3,2018.4,2018.5,2018.6,2018.7,...,2021.3,2021.4,2021.5,2021.6,2021.7,2021.8,2021.9,2021.10,2021.11,2021.12
0,자치구별(1),자치구별(2),사설학원,사설학원,사설학원,사설학원,사설학원,사설학원,사설학원,사설학원,...,사설학원,사설학원,사설학원,사설학원,사설학원,사설학원,사설학원,사설학원,사설학원,사설학원
1,자치구별(1),자치구별(2),학원수 (개),학원수 (개),학원수 (개),학원수 (개),학원수 (개),학원수 (개),학원수 (개),학원수 (개),...,학원수 (개),학원수 (개),학원수 (개),학원수 (개),학원수 (개),학원수 (개),학원수 (개),학원수 (개),학원수 (개),학원수 (개)
2,자치구별(1),자치구별(2),소계,학교교과 교습학원,학교교과 교습학원,학교교과 교습학원,학교교과 교습학원,학교교과 교습학원,학교교과 교습학원,학교교과 교습학원,...,학교교과 교습학원,학교교과 교습학원,학교교과 교습학원,학교교과 교습학원,학교교과 교습학원,평생직업 교육학원,평생직업 교육학원,평생직업 교육학원,평생직업 교육학원,평생직업 교육학원
3,자치구별(1),자치구별(2),소계,소계,입시검정 및 보습,국제화,예능,특수교육,종합,기타,...,국제화,예능,특수교육,종합,기타,직업기술,국제화,인문사회,기예,종합
4,합계,종로구,274,100,73,5,13,1,1,7,...,6,13,0,3,6,35,26,20,29,16
5,합계,중구,119,57,38,7,8,-,1,3,...,9,8,0,1,3,20,9,2,10,3
6,합계,용산구,158,128,65,28,27,-,3,5,...,21,26,0,4,2,10,2,2,5,2
7,합계,성동구,314,268,159,16,69,-,11,13,...,14,55,0,16,9,22,1,3,15,2
8,합계,광진구,430,367,244,25,76,-,5,17,...,23,68,0,7,19,24,5,3,27,3
9,합계,동대문구,363,309,198,17,84,-,5,5,...,16,78,0,4,7,30,3,0,14,4

In [21]:
a.drop(0,inplace=True)
a.drop(1,inplace=True)
a.drop(2,inplace=True)

In [22]:
a=a[["자치구별(2)","2018","2019","2020","2021"]]

In [23]:
a

    자치구별(2)  2018  2019  2020  2021
3   자치구별(2)    소계    소계    소계    소계
4       종로구   274   259   243   217
5        중구   119   118   109    91
6       용산구   158   155   154   137
7       성동구   314   293   289   290
8       광진구   430   406   405   426
9      동대문구   363   368   350   359
10      중랑구   273   276   262   257
11      성북구   464   450   439   451
12      강북구   218   209   206   210
13      도봉구   335   317   297   285
14      노원구   747   740   718   684
15      은평구   521   525   519   509
16     서대문구   345   346   348   342
17      마포구   644   683   689   692
18      양천구  1062  1037  1008   979
19      강서구   707   693   694   697
20      구로구   427   406   394   386
21      금천구   222   224   212   208
22     영등포구   467   446   445   440
23      동작구   458   465   471   487
24      관악구   450   443   431   434
25      서초구  1130  1119  1148  1146
26      강남구  2263  2279  2361  2383
27      송파구  1051  1115  1076  1045
28      강동구   638   672   724   654

In [24]:
a.columns=["자치구별","2018학원수","2019학원수","2020학원수","2021학원수"]

In [26]:
a

       자치구별 2018학원수 2019학원수 2020학원수 2021학원수
3   자치구별(2)      소계      소계      소계      소계
4       종로구     274     259     243     217
5        중구     119     118     109      91
6       용산구     158     155     154     137
7       성동구     314     293     289     290
8       광진구     430     406     405     426
9      동대문구     363     368     350     359
10      중랑구     273     276     262     257
11      성북구     464     450     439     451
12      강북구     218     209     206     210
13      도봉구     335     317     297     285
14      노원구     747     740     718     684
15      은평구     521     525     519     509
16     서대문구     345     346     348     342
17      마포구     644     683     689     692
18      양천구    1062    1037    1008     979
19      강서구     707     693     694     697
20      구로구     427     406     394     386
21      금천구     222     224     212     208
22     영등포구     467     446     445     440
23      동작구     458     465     471     487
24      관악구     450     443     431     434
25      서초구    1130    1119    1148    1146
26      강남구    2263    2279    2361    2383
27      송파구    1051    1115    1076    1045
28      강동구     638     672     724     654

In [28]:
a.drop(3,inplace=True)

In [29]:
a

    자치구별 2018학원수 2019학원수 2020학원수 2021학원수
4    종로구     274     259     243     217
5     중구     119     118     109      91
6    용산구     158     155     154     137
7    성동구     314     293     289     290
8    광진구     430     406     405     426
9   동대문구     363     368     350     359
10   중랑구     273     276     262     257
11   성북구     464     450     439     451
12   강북구     218     209     206     210
13   도봉구     335     317     297     285
14   노원구     747     740     718     684
15   은평구     521     525     519     509
16  서대문구     345     346     348     342
17   마포구     644     683     689     692
18   양천구    1062    1037    1008     979
19   강서구     707     693     694     697
20   구로구     427     406     394     386
21   금천구     222     224     212     208
22  영등포구     467     446     445     440
23   동작구     458     465     471     487
24   관악구     450     443     431     434
25   서초구    1130    1119    1148    1146
26   강남구    2263    2279    2361    2383
27   송파구    1051    1115    1076    1045
28   강동구     638     672     724     654

In [31]:
a.set_index("자치구별",inplace=True)

In [33]:
academy=a

In [34]:
academy=academy.astype(int)

In [35]:
academy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 종로구 to 강동구
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   2018학원수  25 non-null     int32
 1   2019학원수  25 non-null     int32
 2   2020학원수  25 non-null     int32
 3   2021학원수  25 non-null     int32
dtypes: int32(4)
memory usage: 600.0+ bytes

In [36]:
academy.to_csv("C:\\Users\\owner\\team project\\전처리 완\\academy.csv")