## 2020~2022년 : https://www.data.go.kr/data/15067528/fileData.do
## 2018~2019년 : https://data.seoul.go.kr/dataList/OA-15067/S/1/datasetView.do#

In [40]:
# pip install geopy

In [1]:
import numpy as np
import pandas as pd
import os
import time
import googlemaps
from geopy.geocoders import Nominatim
import requests, json, pprint

In [2]:
df=pd.read_excel('C:\\acorn\\midproject\\bus_stop\\raw_data\\20190710기준_서울시정류장정보(수정).xlsx')

In [3]:
df.head()

        표준ID           정류장명  ARS-ID         X좌표        Y좌표
0  100000001        종로2가사거리    1001  126.987750  37.569765
1  100000002    창경궁.서울대학교병원    1002  126.996566  37.579183
2  100000003      명륜3가.성대입구    1003  126.998340  37.582671
3  100000004       종로2가.삼일교    1004  126.987613  37.568579
4  100000005  혜화동로터리.여운형활동터    1005  127.001744  37.586243

In [4]:
def get_address(lat, lng):
    
    try : 
        url = "https://dapi.kakao.com/v2/local/geo/coord2address.json?x="+lng+"&y="+lat
        headers = {"Authorization": "KakaoAK 50164c6bb51aaadf098036960873feca"}
        api_json = requests.get(url, headers=headers)

        full_address = json.loads(api_json.text)

        return full_address['documents'][0]['address']['region_2depth_name']
    
    except : 
        guname = 'error'

In [ ]:
gulist=[]
for i in range(len(df)):
    guname = get_address(str(df['Y좌표'][i]), str(df['X좌표'][i]))
    gulist.append(guname)
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486

In [20]:
len(gulist)

11179

In [21]:
gulist

['종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '서대문구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '서대문구',
 '중구',
 '광진구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '서대문구',
 '종로구',
 '종로구',
 '성동구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '성동구',
 '중구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 None,
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 ...]

In [22]:
df['gu']=gulist

In [23]:
df.head()

        표준ID           정류장명  ARS-ID         X좌표        Y좌표   gu
0  100000001        종로2가사거리    1001  126.987750  37.569765  종로구
1  100000002    창경궁.서울대학교병원    1002  126.996566  37.579183  종로구
2  100000003      명륜3가.성대입구    1003  126.998340  37.582671  종로구
3  100000004       종로2가.삼일교    1004  126.987613  37.568579  종로구
4  100000005  혜화동로터리.여운형활동터    1005  127.001744  37.586243  종로구

In [24]:
len(df)

11179

In [25]:
df.isnull().sum()

표준ID       0
정류장명       0
ARS-ID     0
X좌표        0
Y좌표        0
gu        15
dtype: int64

In [26]:
indices = df.index[df['gu'].isnull()].tolist()
indices

[629,
 2850,
 2868,
 3163,
 4363,
 4472,
 4473,
 4474,
 4482,
 4611,
 6502,
 7875,
 7912,
 8016,
 11067]

In [28]:
for i in indices:
    
    lat = str(df['Y좌표'][i])
    lng = str(df['X좌표'][i])
    
    url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x="+lng+"&y="+lat
    headers = {"Authorization": "KakaoAK 3f4e3aa092149cf60bd447f49294d7c2"}
    api_json = requests.get(url, headers=headers)
    full_address = json.loads(api_json.text)
    
    df['gu'][i] = full_address['documents'][0]['region_2depth_name'] 
    print(i)

C:\Users\khg08\AppData\Local\Temp\ipykernel_12016\2558097193.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gu'][i] = full_address['documents'][0]['region_2depth_name']

629
2850
2868
3163
4363
4472
4473
4474
4482
4611
6502
7875
7912
8016
11067

In [29]:
indices_after = df.index[df['gu'].isnull()].tolist()
indices_after

[]

In [30]:
df.iloc[indices]

            표준ID                정류장명  ARS-ID         X좌표        Y좌표    gu
629    102000055  이태원동남산대림아파트.용산동아파트    3149  126.987449  37.539725   용산구
2850   107900223               브라운스톤    8928  127.017679  37.599298   성북구
2868   107900241               패밀리마트    8910  127.007407  37.609505   성북구
3163   108000375                창문여고    9279  127.035864  37.612134   강북구
4363   111000012              구파발역입구   12012  126.916837  37.637116   은평구
4472   111000138              진관초교입구   12227  126.925847  37.646905   은평구
4473   111000140     푸르지오618동앞.관음사입구   12239  126.929320  37.649611   은평구
4474   111000141     삼천리골입구56사단북한산부대   12230  126.935117  37.650345   은평구
4482   111000149           진관초교관음사입구   12238  126.926869  37.647774   은평구
4611   111000345               입곡삼거리   12440  126.936408  37.649733   은평구
6502   115000538       강서면허시험장메이필트호텔   16839  126.818191  37.550248   강서구
7875   118000169                 대방역   19254  126.924222  37.513005  영등포구
7912   118000207                 대방역   19295  126.923250  37.513230  영등포구
8016   118000525                 대방역   19430  126.924117  37.513020  영등포구
11067  124000444               둔촌습지앞   25316  127.145620  37.521900   강동구

In [31]:
df

            표준ID             정류장명  ARS-ID         X좌표        Y좌표   gu
0      100000001          종로2가사거리    1001  126.987750  37.569765  종로구
1      100000002      창경궁.서울대학교병원    1002  126.996566  37.579183  종로구
2      100000003        명륜3가.성대입구    1003  126.998340  37.582671  종로구
3      100000004         종로2가.삼일교    1004  126.987613  37.568579  종로구
4      100000005    혜화동로터리.여운형활동터    1005  127.001744  37.586243  종로구
...          ...              ...     ...         ...        ...  ...
11174  124900120  고덕1동주민센터.두레근린공원   25529  127.151715  37.558546  강동구
11175  124900121          고덕역1번출구   25518  127.153072  37.555506  강동구
11176  124900122          고덕역1번출구   25528  127.153378  37.555506  강동구
11177  124900123         명일신동아아파트   25520  127.152546  37.552350  강동구
11178  124900124             주양쇼핑   25525  127.153046  37.552346  강동구

[11179 rows x 6 columns]

In [32]:
df.gu.unique()

array(['종로구', '서대문구', '중구', '광진구', '성동구', '용산구', '동대문구', '중랑구', '성북구',
       '노원구', '강북구', '도봉구', '의정부시', '관악구', '은평구', '마포구', '양천구', '구로구',
       '강서구', '강남구', '광명시', '금천구', '안양시 만안구', '영등포구', '동작구', '서초구', '송파구',
       '하남시', '성남시 수정구', '강동구'], dtype=object)

In [33]:
df.to_csv('2019_seoulgg_gu.csv')

In [34]:
seoulgulist = [
    '강남구',
    '강동구',
    '강북구',
    '강서구',
    '관악구',
    '광진구',
    '구로구',
    '금천구',
    '노원구',
    '도봉구',
    '동대문구',
    '동작구',
    '마포구',
    '서대문구',
    '서초구',
    '성동구',
    '성북구',
    '송파구',
    '양천구',
    '영등포구',
    '용산구',
    '은평구',
    '종로구',
    '중구',
    '중랑구'
]

In [35]:
seoulgu = pd.DataFrame(seoulgulist, columns=['gu'])

In [36]:
seoulgu

      gu
0    강남구
1    강동구
2    강북구
3    강서구
4    관악구
5    광진구
6    구로구
7    금천구
8    노원구
9    도봉구
10  동대문구
11   동작구
12   마포구
13  서대문구
14   서초구
15   성동구
16   성북구
17   송파구
18   양천구
19  영등포구
20   용산구
21   은평구
22   종로구
23    중구
24   중랑구

In [37]:
result = pd.merge(df, seoulgu)
result

            표준ID             정류장명  ARS-ID         X좌표        Y좌표   gu
0      100000001          종로2가사거리    1001  126.987750  37.569765  종로구
1      100000002      창경궁.서울대학교병원    1002  126.996566  37.579183  종로구
2      100000003        명륜3가.성대입구    1003  126.998340  37.582671  종로구
3      100000004         종로2가.삼일교    1004  126.987613  37.568579  종로구
4      100000005    혜화동로터리.여운형활동터    1005  127.001744  37.586243  종로구
...          ...              ...     ...         ...        ...  ...
11160  124900120  고덕1동주민센터.두레근린공원   25529  127.151715  37.558546  강동구
11161  124900121          고덕역1번출구   25518  127.153072  37.555506  강동구
11162  124900122          고덕역1번출구   25528  127.153378  37.555506  강동구
11163  124900123         명일신동아아파트   25520  127.152546  37.552350  강동구
11164  124900124             주양쇼핑   25525  127.153046  37.552346  강동구

[11165 rows x 6 columns]

In [38]:
len(df)-len(result)

14

In [39]:
result.gu.unique()

array(['종로구', '서대문구', '중구', '광진구', '성동구', '용산구', '동대문구', '중랑구', '성북구',
       '노원구', '강북구', '도봉구', '관악구', '은평구', '마포구', '양천구', '구로구', '강서구',
       '강남구', '금천구', '영등포구', '동작구', '서초구', '송파구', '강동구'], dtype=object)

In [40]:
result.to_csv('bus_2019.csv')

#### 구별 정류장개수 구하기

In [41]:
result

            표준ID             정류장명  ARS-ID         X좌표        Y좌표   gu
0      100000001          종로2가사거리    1001  126.987750  37.569765  종로구
1      100000002      창경궁.서울대학교병원    1002  126.996566  37.579183  종로구
2      100000003        명륜3가.성대입구    1003  126.998340  37.582671  종로구
3      100000004         종로2가.삼일교    1004  126.987613  37.568579  종로구
4      100000005    혜화동로터리.여운형활동터    1005  127.001744  37.586243  종로구
...          ...              ...     ...         ...        ...  ...
11160  124900120  고덕1동주민센터.두레근린공원   25529  127.151715  37.558546  강동구
11161  124900121          고덕역1번출구   25518  127.153072  37.555506  강동구
11162  124900122          고덕역1번출구   25528  127.153378  37.555506  강동구
11163  124900123         명일신동아아파트   25520  127.152546  37.552350  강동구
11164  124900124             주양쇼핑   25525  127.153046  37.552346  강동구

[11165 rows x 6 columns]

In [42]:
result1=result.groupby('gu').count()

In [43]:
result1

      표준ID  정류장명  ARS-ID  X좌표  Y좌표
gu
강남구    548   548     548  548  548
강동구    385   385     385  385  385
강북구    448   448     448  448  448
강서구    603   603     603  603  603
관악구    485   485     485  485  485
광진구    292   292     292  292  292
구로구    513   513     513  513  513
금천구    362   362     362  362  362
노원구    544   544     544  544  544
도봉구    391   391     391  391  391
동대문구   319   319     319  319  319
동작구    447   447     447  447  447
마포구    568   568     568  568  568
서대문구   446   446     446  446  446
서초구    649   649     649  649  649
성동구    442   442     442  442  442
성북구    604   604     604  604  604
송파구    429   429     429  429  429
양천구    365   365     365  365  365
영등포구   504   504     504  504  504
용산구    344   344     344  344  344
은평구    511   511     511  511  511
종로구    375   375     375  375  375
중구     211   211     211  211  211
중랑구    380   380     380  380  380

In [45]:
result2 = pd.DataFrame(result1['정류장명'], index=result1.index)
result2

      정류장명
gu
강남구    548
강동구    385
강북구    448
강서구    603
관악구    485
광진구    292
구로구    513
금천구    362
노원구    544
도봉구    391
동대문구   319
동작구    447
마포구    568
서대문구   446
서초구    649
성동구    442
성북구    604
송파구    429
양천구    365
영등포구   504
용산구    344
은평구    511
종로구    375
중구     211
중랑구    380

In [46]:
result2.columns=["정류장수"]

In [47]:
result2

      정류장수
gu
강남구    548
강동구    385
강북구    448
강서구    603
관악구    485
광진구    292
구로구    513
금천구    362
노원구    544
도봉구    391
동대문구   319
동작구    447
마포구    568
서대문구   446
서초구    649
성동구    442
성북구    604
송파구    429
양천구    365
영등포구   504
용산구    344
은평구    511
종로구    375
중구     211
중랑구    380

In [48]:
result2['정류장수'].sum()

11165

In [49]:
result2.to_csv('2019_bus_count.csv')

In [52]:
len(result2)

25