# 중학교 데이터
## 국공립, 사립 중학교 데이터 포함

In [ ]:
import pandas as pd

### 데이터 출처
    - https://data.seoul.go.kr/dataList/datasetList.do#

In [4]:
data1=pd.read_csv("C:\\Users\\owner\\team project\\중학교(국·공립)_20230417163307.csv")

In [6]:
del data1["자치구별(1)"]

In [9]:
# 컬럼명 변경
data1.columns=["자치구별","2018학교수","2019학교수","2020학교수","2021학교수","2022학교수"]

In [10]:
data1

       자치구별  2018학교수  2019학교수  2020학교수  2021학교수  2022학교수
0   자치구별(2)  학교수 (개)  학교수 (개)  학교수 (개)  학교수 (개)  학교수 (개)
1        소계      276      277      278      280      281
2        국립        2        2        2        2        2
3        공립      274      275      276      278      279
4       종로구        2        2        2        2        2
5        중구        4        4        4        4        4
6       용산구        4        4        4        4        4
7       성동구       10       10       10       10       10
8       광진구        9        9        9        9        9
9      동대문구        9        9        9        9        9
10      중랑구       11       11       11       11       11
11      성북구       10       10       10       10       10
12      강북구        8        8        8        8        8
13      도봉구       11       11       11       11       11
14      노원구       21       21       21       21       21
15      은평구       11       11       11       11       11
16     서대문구        7        7        7        7        7
17      마포구        9        9        9        9        9
18      양천구       16       16       16       16       16
19      강서구       16       16       16       16       16
20      구로구       12       12       13       13       13
21      금천구        7        7        7        7        7
22     영등포구       11       11       11       12       12
23      동작구       12       12       12       12       12
24      관악구       12       12       12       12       12
25      서초구       13       13       13       13       13
26      강남구       18       18       18       18       18
27      송파구       21       22       22       22       23
28      강동구       12       12       12       13       13

In [20]:
# 자치구별 인덱스 설정
data1.set_index("자치구별",inplace=True)

In [25]:
# 필요없는 데이터 삭제
data1.drop("자치구별(2)",inplace=True)
data1.drop("소계",inplace=True)
data1.drop("국립",inplace=True)
data1.drop("공립",inplace=True)

KeyError: "['자치구별(2)'] not found in axis"

In [24]:
data1

     2018학교수 2019학교수 2020학교수 2021학교수 2022학교수
자치구별
종로구        2       2       2       2       2
중구         4       4       4       4       4
용산구        4       4       4       4       4
성동구       10      10      10      10      10
광진구        9       9       9       9       9
동대문구       9       9       9       9       9
중랑구       11      11      11      11      11
성북구       10      10      10      10      10
강북구        8       8       8       8       8
도봉구       11      11      11      11      11
노원구       21      21      21      21      21
은평구       11      11      11      11      11
서대문구       7       7       7       7       7
마포구        9       9       9       9       9
양천구       16      16      16      16      16
강서구       16      16      16      16      16
구로구       12      12      13      13      13
금천구        7       7       7       7       7
영등포구      11      11      11      12      12
동작구       12      12      12      12      12
관악구       12      12      12      12      12
서초구       13      13      13      13      13
강남구       18      18      18      18      18
송파구       21      22      22      22      23
강동구       12      12      12      13      13

In [26]:
data2=pd.read_csv("C:\\Users\\owner\\team project\\중학교(사립)_20230417163450.csv")

In [27]:
data2

    자치구별(1)  자치구별(2)     2018     2019     2020     2021     2022
0   자치구별(1)  자치구별(2)  학교수 (개)  학교수 (개)  학교수 (개)  학교수 (개)  학교수 (개)
1        합계       소계      109      109      109      109      109
2        합계      종로구        7        7        7        7        7
3        합계       중구        4        4        4        4        4
4        합계      용산구        5        5        5        5        5
5        합계      성동구        1        1        1        1        1
6        합계      광진구        3        3        3        3        3
7        합계     동대문구        6        6        6        6        6
8        합계      중랑구        3        3        3        3        3
9        합계      성북구        8        8        8        8        8
10       합계      강북구        5        5        5        5        5
11       합계      도봉구        2        2        2        2        2
12       합계      노원구        5        5        5        5        5
13       합계      은평구        7        7        7        7        7
14       합계     서대문구        7        7        7        7        7
15       합계      마포구        5        5        5        5        5
16       합계      양천구        3        3        3        3        3
17       합계      강서구        6        6        6        6        6
18       합계      구로구        1        1        1        1        1
19       합계      금천구        2        2        2        2        2
20       합계     영등포구        -        -        -        -        -
21       합계      동작구        4        4        4        4        4
22       합계      관악구        4        4        4        4        4
23       합계      서초구        3        3        3        3        3
24       합계      강남구        6        6        6        6        6
25       합계      송파구        6        6        6        6        6
26       합계      강동구        6        6        6        6        6

In [28]:
del data2["자치구별(1)"]

In [29]:
# 컬럼명 변경
data2.columns=["자치구별","2018학교수","2019학교수","2020학교수","2021학교수","2022학교수"]

In [30]:
# 자치구별 인덱스 설정
data2.set_index("자치구별",inplace=True)

In [33]:
data2

     2018학교수 2019학교수 2020학교수 2021학교수 2022학교수
자치구별
종로구        7       7       7       7       7
중구         4       4       4       4       4
용산구        5       5       5       5       5
성동구        1       1       1       1       1
광진구        3       3       3       3       3
동대문구       6       6       6       6       6
중랑구        3       3       3       3       3
성북구        8       8       8       8       8
강북구        5       5       5       5       5
도봉구        2       2       2       2       2
노원구        5       5       5       5       5
은평구        7       7       7       7       7
서대문구       7       7       7       7       7
마포구        5       5       5       5       5
양천구        3       3       3       3       3
강서구        6       6       6       6       6
구로구        1       1       1       1       1
금천구        2       2       2       2       2
영등포구       -       -       -       -       -
동작구        4       4       4       4       4
관악구        4       4       4       4       4
서초구        3       3       3       3       3
강남구        6       6       6       6       6
송파구        6       6       6       6       6
강동구        6       6       6       6       6

In [32]:
# 필요없는 데이터 삭제
data2.drop("자치구별(2)",inplace=True)
data2.drop("소계",inplace=True)

KeyError: "['국립'] not found in axis"

In [53]:
data1=data1.astype(int)
data2=data2.replace("-",0).astype(int)

In [51]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 종로구 to 강동구
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   2018학교수  25 non-null     int32
 1   2019학교수  25 non-null     int32
 2   2020학교수  25 non-null     int32
 3   2021학교수  25 non-null     int32
 4   2022학교수  25 non-null     int32
dtypes: int32(5)
memory usage: 1.2+ KB

In [52]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 종로구 to 강동구
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   2018학교수  25 non-null     int32
 1   2019학교수  25 non-null     int32
 2   2020학교수  25 non-null     int32
 3   2021학교수  25 non-null     int32
 4   2022학교수  25 non-null     int32
dtypes: int32(5)
memory usage: 1.2+ KB

In [66]:
middle_school=data1.merge(data2, on="자치구별")

In [71]:
# 국공립학교 데이터와 사립학교 데이터 합치기
middle_school=data1+data2

In [68]:
middle_school

      2018학교수  2019학교수  2020학교수  2021학교수  2022학교수
자치구별
종로구         9        9        9        9        9
중구          8        8        8        8        8
용산구         9        9        9        9        9
성동구        11       11       11       11       11
광진구        12       12       12       12       12
동대문구       15       15       15       15       15
중랑구        14       14       14       14       14
성북구        18       18       18       18       18
강북구        13       13       13       13       13
도봉구        13       13       13       13       13
노원구        26       26       26       26       26
은평구        18       18       18       18       18
서대문구       14       14       14       14       14
마포구        14       14       14       14       14
양천구        19       19       19       19       19
강서구        22       22       22       22       22
구로구        13       13       14       14       14
금천구         9        9        9        9        9
영등포구       11       11       11       12       12
동작구        16       16       16       16       16
관악구        16       16       16       16       16
서초구        16       16       16       16       16
강남구        24       24       24       24       24
송파구        27       28       28       28       29
강동구        18       18       18       19       19

In [70]:
middle_school.to_csv("C:\\Users\\owner\\team project\\전처리 완\\middle_school.csv")